### ISSUE TITLE
LWG3534 ranges::set_intersection and ranges::set_difference algorithm requirements are too strict

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1021]
Issue: https://cplusplus.github.io/LWG/issue3534

During the LWG prioritization poll it was suggested that this is a design change and should be seen by LEWG, maybe as a paper. Please take a look and let us know if you'd like the LWG issue closed, and a paper solicited to change it.

**Comment by inbal2l** [comment]
SG9 have looked at the issue. The preferences is not to have the concept as "// exposition only", Alexander have volunteered to explore the concept (and name) in a paper. 
Forwarding the issue to LEWG.

**Comment by brycelelbach** [comment]
We need the paper first.

**Comment by brycelelbach** [comment]
Closing due to more than 1 year of inactivity. Please re-open if further work is expected.
