### ISSUE TITLE
LWG3564: Does const-qualification affect transform_view elements?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1052]
SG9 needs to clarify the intended design for https://cplusplus.github.io/LWG/issue3564

**Comment by inbal2l** [comment]
This topic was discussed at SG9 and in a mail thread.
The resulted behavior is agreed on (equality), but the solution proposed in the issue did not got consensus, we will discuss it again in Sep 13th meeting.

**Comment by inbal2l** [comment]
SG9 have seen this again on 09-13 ([Minutes](https://wiki.edg.com/bin/view/Wg21telecons2021/LWG3564#SG9-2021-09-13)) and decided to move on with the suggested fix (we believe it leaves room for a future change). We also requested a policy paper, which Casey have volunteered to prepare, to address the more general design question.

**Comment by JeffGarland** [comment]
Issue has been resolved in the working paper - closing.

[2022-07-15; LWG telecon: move to Ready]
[2022-07-25 Approved at July 2022 virtual plenary. Status changed: Ready → WP.]
