### ISSUE TITLE
Pacman moves alone when he dies

### ISSUE THREAD

**Issue by cor3ntin** [cplusplus/papers#1069]

**Comment by jwakely** [comment]
I assume this was meant to be an issue in another repo.

**Comment by cor3ntin** [comment]
Oh gosh

**Comment by DBJDBJ** [comment]
Too late M8, history has been made 🥇

**Comment by MenaceInc** [comment]
I would love to know what repo this would be suited to...

**Comment by zygoloid** [comment]
https://github.com/mod-cpp/pacman/issues/16

**Comment by DBJDBJ** [comment]
> 
> 
> I would love to know what repo this would be suited to...

`std::pacman` one can safely assume?
