### ISSUE TITLE
P2418R0 Add support for `std::generator`-like types to `std::format`

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1088]
[P2418R0](https://isocpp.org/files/papers/P2418R0.html) Add support for `std::generator`-like types to `std::format` (Victor Zverovich)

**Comment by JohelEGP** [comment]
The title and the text don't match. Looking at the author, I suppose the title is right.

**Comment by brycelelbach** [comment]
Thanks, copy paste mistake.

**Comment by h-vetinari** [comment]
This issue and #1092 are duplicating each other. Even though this issue came before #1092, it's perhaps better to close this one.

**Comment by jensmaurer** [comment]
Yes, manually creating issues when not following the exact pattern confuses the import bot.
