### ISSUE TITLE
LWG3579: Complexity guarantees for resize() and append() functions across the library

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1091]
LWG thinks this is out of scope for the issues list, so LEWG should consider it:

https://cplusplus.github.io/LWG/issue3579

**Comment by billy-baker** [comment]
Reviewed in 2022-02-22 LEWG telecon.

__POLL:__ LWG3579 Complexity guarantees for resize() and append() functions across the library should be closed as NAD. (A paper would be needed for changes.)

No objection to unanimous consent to close as NAD.

As stated in the poll, a paper would be needed. Such a paper would need to include discussion on whether allocate_at_least (new for C++23) has an impact.

**Comment by jwakely** [comment]
Issue closed as NAD

**Comment by JeffGarland** [comment]
@jwakely I'm closing the github issue since this is closed.
