### ISSUE TITLE
LWG3611: Should compare_exchange be allowed to modify the expected value on success?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1116]
LWG would like SG1 to advise on https://cplusplus.github.io/LWG/issue3611

As noted in the issue, this is revisiting https://cplusplus.github.io/LWG/issue2426

There was a thread on the SG1 list about it in December 2020, subject "atomic compare_exchange and padding bits".

**Comment by jwakely** [comment]
As the submitter of the issue, I'm OK with the answer being "no, it can't modify `expected` on success", but I'd like a clear statement one way or the other so we can record it in the LWG issues list.

**Comment by ogiroux** [comment]
In response to LWG 3611, allow compare_exchange to modify the expected value on success.
SF F N A SA
0  0 0 5 4

**Comment by jwakely** [comment]
Issue updated to Tentatively NAD status - thanks.
