### ISSUE TITLE
LWG3646: std::ranges::view_interface::size returns a signed type

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1182]
LWG would like LEWG to review the proposed resolution for this issue:
https://cplusplus.github.io/LWG/issue3646

**Comment by inbal2l** [comment]
I'll start an LEWG ML thread (CCing SG9) to review it.

**Comment by brycelelbach** [comment]
We'll send this to mailing list review as soon as we can (next few weeks).

**Comment by brycelelbach** [comment]
[A motion was made on 2022-02-21 to move this paper directly from mailing list review to electronic polling](http://lists.isocpp.org/lib-ext/2022/02/22588.php). The motion passed with 10 +1s.

**Comment by brycelelbach** [comment]
## [2022-05 Library Evolution Electronic Poll Outcomes](https://wg21.link/P2575)

__POLL: Send the proposed resoluton in [LWG3646] ranges::view_interface::size Returns A Signed Type to Library Working Group for C++23, classified as an improvement of an existing feature ([P0592R4] bucket 2 item).__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|10|9|0|0|0|

Unanimous consensus in favor.

**Comment by JeffGarland** [comment]
Tentatively ready poll started on LWG list 2022-07-04

**Comment by jwakely** [comment]
Status set to Tentatively Ready

**Comment by JeffGarland** [comment]
This issue was moved in Kona and is now in the working paper for c++23 -- closing.
