### ISSUE TITLE
LWG3656: Inconsistent bit operations returning a count

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1183]
LWG polling had consensus to make this issue Tentatively Ready, although we'd like LEWG to affirm that decision before changing its status:
https://cplusplus.github.io/LWG/issue3656

**Comment by brycelelbach** [comment]
We'll send this to mailing list review as soon as we can (next few weeks).

**Comment by billy-baker** [comment]
Reviewed in LEWG telecon 2022-02-22

__POLL:__ Send the proposed resolution for LWG3656 "Inconsistent bit operations returning a count" to LWG for C++23.

No objection to unanimous consent to send the proposed resolution for LWG3656 to LWG for C++23.

The changes in P1956 changed the functions to be more counting than mathematical.

**Comment by JeffGarland** [comment]
List review completed 2022-07-08 with 10 TR votes.

**Comment by JeffGarland** [comment]
Closing this item -- from the issue: [2022-07-25 Approved at July 2022 virtual plenary. Status changed: Ready → WP.]
