### ISSUE TITLE
LWG3659: Consider ATOMIC_FLAG_INIT undeprecation

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1184]
LWG would like SG1 to review this issue:
https://cplusplus.github.io/LWG/issue3659

**Comment by ogiroux** [comment]
In response to LWG 3659, add ATOMIC_FLAG_INIT to <stdatomic.h> as undeprecated.
SF F N A SA
3  0 0 0 0

In response to LWG 3659, undeprecate ATOMIC_FLAG_INIT in <atomic>.
SF F N A SA
2  3 1 0 0

**Comment by jwakely** [comment]
LWG3659 was resolved at the July plenary.
