### ISSUE TITLE
P2532 Removing exception_ptr from the Receiver Concepts

### ISSUE THREAD

**Issue by ben-craig** [cplusplus/papers#1185]
[P2532R0](https://wg21.link/p2532r0) Removing exception_ptr from the Receiver Concepts (Eric Niebler)

**Comment by ben-craig** [comment]
## D2532R0: Removing exception_ptr from the Receiver Concepts

[P2532R0](https://wg21.link/P2532R0): Removing exception_ptr from the Receiver Concepts

[2022-02-01 Library Evolution Telecon Minutes](http://wiki.edg.com/bin/view/Wg21telecons2022/P2532#Library-Evolution-2022-02-01)

__Chair:__ Ben Craig

__Champion:__ Eric Niebler

__Minute Taker:__ Inbal Levi

__SUMMARY:__ 
Discussed an approach to reduce the reliance on exception_ptr in P2300.  This involves making sender::set_value noexcept, and increased reliance on the completion_signatures facility.

__OUTCOME:__

__POLL: Apply D2532R0 and related exception_ptr changes to P2300, for C++23, with changes reviewed by a Committee of Ben Craig, Mark Hoemmen, and Bryan St. Amour (not going through electronic polling).__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|12|9|2|0|0|

__Attendance:__ 36

__# of Authors:__ 1

__Author Position:__ SF

__Outcome:__ Strong Consensus

**Comment by brycelelbach** [comment]
Incorporated into P2300 (#1054).
