### ISSUE TITLE
CWG2507: Default arguments for operator[]

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1217]
CWG would like EWG to confirm that default arguments were intended to be permitted for an `operator[]` function. See [P2128R6](https://wg21.link/p2128r6) for the paper removing restrictions on overloaded `operator[]`.

See CWG2507:

The adopted wording did not address the following restriction from 12.4.1 [[over.oper.general](https://wg21.link/over.oper.general#10)] paragraph 10:

> An operator function cannot have default arguments (9.3.4.7 [[dcl.fct.default](https://wg21.link/dcl.fct.default)]), except where explicitly stated below.

**Comment by erichkeane** [comment]
EWG Discussed this issue during the [April 14, 2022 telecon](https://wiki.edg.com/bin/view/Wg21telecons2022/EWG-2022-04-14).  The following poll was taken:

Instruct core to resolve CWG2507 as proposed in the issue for C++23.

| SF | F | N | A | SA |
|-|-|-|-|-|
| 8  | 4 | 1 | 0 | 0  |

Result: Consensus

Based on feedback and results, the EWG chair encourages CWG to act on this immediately, and this will not be sent to electronic polling.

**Comment by jensmaurer** [comment]
CWG telecon 2022-04-22: Approved for plenary vote.
