### ISSUE TITLE
CWG2569 Use of decltype(capture) in a lambda's parameter-declaration-clause

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1227]
See https://cplusplus.github.io/CWG/issues/2569.html
and the reflector thread starting at http://lists.isocpp.org/core/2022/04/12341.php

In short, [P2036R3](https://wg21.link/p2036r3) #766 was approved as a Defect Report, but its changes make popular existing standard library implementations ill-formed. Thus, there is concern about too much breakage, in particular with the "DR" aspect of P2036R3.

Some possible approaches how to proceed are listed in the issue.

**Comment by jensmaurer** [comment]
See https://isocpp.org/files/papers/D2579R0.pdf

**Comment by erichkeane** [comment]
EWG Reviewed [D2579R0 ](https://isocpp.org/files/papers/D2579R0.pdf) during its [2022-5-12](https://wiki.edg.com/bin/view/Wg21telecons2022/EWG-2022-05-12) telecon, the following polls were taken:

Revert P2036R3 completely from C++23, leaving us with the C++20 and before behavior.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  4 | 3 | 2 | 3 |  2 |

Result: Not Consensus

Leave P2036R3 in the C++23 standard, however no longer treat it as a Defect Report, making it a breaking change in C++23.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  0 | 1 | 2 | 8 |  4 |

Result: Consensus Against.

Accept Option D from D2579R0, which requires look-ahead for the parameter list but leave referring to captures in the template parameter list/first-requires-clause as ill-formed.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  0 | 3 | 4 | 5 |  2 |

Result Consensus Against.


Accept Option E from D2579R0, which treats all captures as non-const for all places before the 'mutable' keyword.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  3 | 8 | 3 | 0 |  0 |

Result: Consensus --> to electronic polling.


**NOTE: The following poll was taken later in the telecon, after two members had left the room.  The result of this poll is that D2579R0 is a direct modification of P2036R3, and thus ALSO applies as a Defect Report.** 

Leave P2036R3 in the C++23 standard with the modifications of Option E above, however no longer treat it as a Defect Report, making it a breaking change in C++23.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  2 | 3 | 5 | 1 |  1 |

Result: No Consensus(neutrals).

**Comment by jfbastien** [comment]
This was voted on in the June 2022 EWG polls. [Results are here](https://isocpp.org/files/papers/P1018R17.html#polls).

<ul style="margin-left: 0px; padding-left: 2em; color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li data-md="" style="margin: 0.25em 0px 0.5em; padding: 0px; position: relative;"><p style="margin: 0px;"><strong>🗳 Poll:</strong><span> </span>Accept Option E from D2579R0 as a resolution to CWG2569, which treats all captures as non-<code class="highlight" style="font-family: Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, Monaco, monospace; font-size: 0.9em; hyphens: none; text-transform: none; text-align: start; font-variant: normal; orphans: 3; widows: 3; break-before: avoid; padding: 0.1em; border-radius: 0.3em; background: rgba(255, 255, 255, 0.05);"><c- k="" style="color: rgb(211, 54, 130);">const</c-></code><span> </span>for all places before the<span> </span><code class="highlight" style="font-family: Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, Monaco, monospace; font-size: 0.9em; hyphens: none; text-transform: none; text-align: start; font-variant: normal; orphans: 3; widows: 3; break-before: avoid; padding: 0.1em; border-radius: 0.3em; background: rgba(255, 255, 255, 0.05);"><c- k="" style="color: rgb(211, 54, 130);">mutable</c-></code><span> </span>keyword.</p></li></ul><p style="margin: 1em 0px; color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Poll votes:</strong></p>

SF | F | N | A | SA
-- | -- | -- | -- | --
5 | 12 | 5 | 1 | 1
Abstain: 4

<br style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Poll outcome:</strong><span style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>✅ consensus</span>

**Comment by jensmaurer** [comment]
CWG telecon 2022-07-01: Approved P2579R0, addressing CWG2569.
