### ISSUE TITLE
CWG2586 Explicit object parameter for assignment and comparison 

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1235]
See CWG2586.

It's pretty obvious that the situation for comparison operators is a wording oversight, but it's less obvious whether the relaxation of the rules is desirable for copy/move assignment operators, since those are a lot more restricted in the status quo (they can't be friends, for example).

**Comment by erichkeane** [comment]
This was discussed during the [June 9, 2022](https://wiki.edg.com/bin/view/Wg21telecons2022/EWG-2022-06-10) EWG, and the following polls were taken:

EWG agrees with the direction of the proposed resolution in CWG2586.

| SF | F | N | A | SA |
|----|---|---|---|----|
|  3 | 6 | 1 | 0 |  0 |
Result: Consensus

Due to some implementation concerns, we require this resolution to go through EWG electronic polling.

**Comment by jfbastien** [comment]
This was voted on in the June 2022 EWG polls. [Results are here](https://isocpp.org/files/papers/P1018R17.html#polls).

<ul style="margin-left: 0px; padding-left: 2em; color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li data-md="" style="margin: 0.25em 0px 0.5em; padding: 0px; position: relative;"><p style="margin: 0px;"><strong>🗳 Poll:</strong><span> </span>Adopt CWG2586’s suggested resolution to resolve CWG2586.</p></li></ul><p style="margin: 1em 0px; color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Poll votes:</strong></p>

SF | F | N | A | SA
-- | -- | -- | -- | --
8 | 15 | 2 | 0 | 0
Abstain: 3

<br style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Poll outcome:</strong><span style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>✅ consensus</span><br class="Apple-interchange-newline">

**Comment by jensmaurer** [comment]
CWG telecon 2022-07-15: Approved.
