### ISSUE TITLE
P0323R11 (std::expected) correction in 5.3.1

### ISSUE THREAD

**Issue by RishabhRD** [cplusplus/papers#1254]
In section 5.3.1 for the constructor:
```cpp
template<class U, class... Args>
    constexpr explicit unexpected(in_place_t, initializer_list<U>, Args&&...);
```
constraints are given as:
```cpp
is_constructible_v<E, initializer_list<U>&, Args...>
```

However, effect of this constructor is described as: "Effects: Direct-non-list-initializes val with ``std::forward<Args>(args)....``"

This doesn't seem to be correct as it doesn't match with constraints and initializer_list<U> is unused.
I guess this should be changed to :
```cpp
val(lst, std::forward<Args>(args)...)
```
where lst is instance of ``std::initializer_list<U>``

Thanks

**Comment by JohelEGP** [comment]
This should have been filed against https://github.com/cplusplus/draft/. And it was fixed with https://github.com/cplusplus/draft/commit/71f6e85eaa6bba99f6901074eebeabc9f3352719#diff-afa9f66c3857a24dc4092685af2cbf9cbc44bbd35afa4b0eb26a14a324b0999dR6630.
