### ISSUE TITLE
LWG3714 Non-single-argument constructors for range adaptors should not be explicit

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1257]
Issue: https://cplusplus.github.io/LWG/issue3714

During the LWG prioritization poll it was suggested that we need LEWG to decide on a consistent policy before we can make any consistency fix here. Please take a look and let us know what LEWG wants here.

**Comment by billy-baker** [comment]
The topic was presented in the LEWG 2022-07-19 telecon. The issue has been referred to SG9 Ranges for guidance.  For consistency, the views listed in the issue as well as views that are in flight such as cartesian_product_view need to be reviewed. There was some previous discussion on the topic of explicit constructors for P1899 stride_view.

**Comment by inbal2l** [comment]
Scheduled for SG9 on 10-10-2022

**Comment by inbal2l** [comment]
SG9 (Ranges) reviewed the issue on 2022-10-10, the review included Ville's paper on the same subject [PXXXXR0: Ruminations on explicit multi-param constructors of views](https://wiki.edg.com/pub/Wg21telecons2022/SG9/view-explicit-ctors.html)  ([Full Minutes](https://wiki.edg.com/bin/view/Wg21telecons2022/P2602#SG9-2022-10-10)).

### Polls

__POLL: We support applying “LWG3714: Non-single-argument constructors for range adaptors should not be explicit” AKA option 2 in Ville’s paper: “Drop the explicit from the C++23 views” to C++23 (possibly as an NB comment, if needed)__

|SF|F|N|A|SA|
|-|-|-|-|-|
|   1|  4 |   3|  2 |  0  |

__Attendance:__ 10

__Author’s position:__ SF

__Outcome:__ Weak recommendation in favor (no consensus)


__POLL: We support apply option 1 in Ville’s paper: “Make the C++20 view multi-param constructors explicit too” to C++20__

|SF|F|N|A|SA|
|-|-|-|-|-|
|  0 | 6  |  3 |  0 | 0   |

__Attendance:__ 10

__Author’s position:__ WF

__Outcome:__ Consensus in favor

### Summary
The second poll had more consensus. The polls indicate that SG9 support making the C++20 view multi-param constructors explicit (as a C++20 DR / Fix), recommendation is passed to LEWG.

**Comment by brycelelbach** [comment]
@JeffGarland can you close this LWG issue, as we're proceeding with P2711.
