### ISSUE TITLE
P2604 mdspan: rename pointer and contiguous

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1258]
[P2604R0](https://wg21.link/P2604R0) mdspan: rename pointer and contiguous (Christian Trott)

**Comment by JeffGarland** [comment]
LWG reviewed and approved 2022-06-24 

Notes: https://wiki.edg.com/bin/view/Wg21telecons2022/P2604-20220624
poll: Put P2604R0 into C++23 pending LEWG approval

F | A | N
-- | -- | --
17 | 0 | 0

**Comment by brycelelbach** [comment]
## [2022-07 Library Evolution Electronic Poll Outcomes](https://wg21.link/P2611)

__Poll 1.13: Send [P2604R0] mdspan: Rename pointer, data, And contiguous to Library Working Group for C++23, classified as an improvement of an existing feature ([P0592R4] bucket 2 item).__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|13|13|0|0|0|

__Outcome: Unanimous consensus in favor.__

**Comment by tkoeppe** [comment]
This has been applied.
