### ISSUE TITLE
P1019 Integrating Executors with Parallel Algorithms

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#127]
[P1019R2](https://wg21.link/p1019r2) Integrating Executors with Parallel Algorithms (Jared Hoberock)

https://issues.isocpp.org/show_bug.cgi?id=488

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1019R2-SG1).

**Comment by ogiroux** [comment]
Needs further work.

**Comment by ogiroux** [comment]
I asked the originating team if they plan a revision, and they indicated that they do not. Closing this issue.
