### ISSUE TITLE
CWG2597 Replaceable allocation and deallocation functions in the global module

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1273]
Subclause 10.1 [[module.unit paragraph 7](https://wg21.link/module.unit#7)]  implicitly attaches the replaceable global allocation or deallocation functions to the global module. Now that extern "C++" can be used to introduce declarations in the global module, even when in the purview of a named module, the provision seems superfluous.

https://cplusplus.github.io/CWG/issues/2597.html

Example:

```
module M;
void * operator new(std::size_t);  // before: well-formed; after: ill-formed because attachment conflict with the predeclared version
extern "C++" void * operator new(std::size_t);   // well-formed before and after
```

This is a user-visible design change, imposing a small ergonomic cost for a rare case in exchange for the removal of a special case, and thus should have EWG approval.

**Comment by ChuanqiXu9** [comment]
Should we change the suggested wording into the following? 
```
and should be attached to the global module, otherwise the program is ill-formed.
```

Otherwise, I might recognize the example is well-formed personally.
```
module M;
void * operator new(std::size_t);
```

**Comment by jensmaurer** [comment]
CWG telecon 2022-07-15: Approved.

**Comment by tkoeppe** [comment]
This has been applied.
