### ISSUE TITLE
P1097 Named character escapes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#130]
[P1097R2](https://wg21.link/p1097r2) Named character escapes (R. Martinho Fernandes)

**Comment by tahonermann** [comment]
This paper is ready for EWG.  It received strong support in EWGI in San Diego (http://wiki.edg.com/bin/view/Wg21sandiego2018/P1097R1).  Removing the SG16 label.

**Comment by davidstone** [comment]
This paper was discussed in EWG in Belfast. There was encouragement for further work in this area as a language feature, but we do not have consensus to adopt the feature for C++23 at this time.

**Comment by tahonermann** [comment]
This paper has been superseded by [P2071](https://github.com/cplusplus/papers/issues/798).  Closing.
