### ISSUE TITLE
LWG3767 codecvt<charN_t, char8_t, mbstate_t> incorrectly added to locale

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1310]
LWG would like SG16 to take a look at this issue:

https://cplusplus.github.io/LWG/issue3767

**Comment by tahonermann** [comment]
SG16 discussed this issue during its [2020-09-28 telecon](https://github.com/sg16-unicode/sg16-meetings/#september-28th-2022). The following poll was taken:

- **Poll 1: SG16 agrees that the codecvt facets mentioned in LWG3767 "codecvt<charN_t, char8_t, mbstate_t> incorrectly added to locale" are intended to be invariant with respect to locale.**
  - Attendance: 7
    | SF  | F   | N   | A   | SA  |
    | --: | --: | --: | --: | --: |
    |   4 |   3 |   0 |   0 |   0 |
  - Consensus: unanimously in favor.

SG16 did not attempt to establish a position with regard to any particular resolution to the issue. Removal or deprecation of the relevant facets and the proposed change to the accessibility of the `std::codecvt` destructor have consequences that are best considered by LEWG and LWG.

**Comment by jwakely** [comment]
Let's close this - the ball is back in the LWG issues list court now. Thanks, @tahonermann and SG16.
