### ISSUE TITLE
LWG3756 Is the std::atomic_flag class signal-safe?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1311]
LWG would like SG1 to take a look at this issue:

https://cplusplus.github.io/LWG/issue3756

**Comment by ogiroux** [comment]
Poll: Adopt the proposed resolution for LWG3756
  "f is a non-static member function invoked on an 
    atomic_flag object, or"
  "f is a non-member function, and every pointer-to-
    atomic argument passed to f is atomic_flag, or"
SF F N A SA
11 3 0 0 0

Unanimous consent

**Comment by jwakely** [comment]
Thanks, ownership transferred back to the LWG issues list.

**Comment by jwakely** [comment]
Approved in Issaquah 2023:
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2789r0.html#3756
