### ISSUE TITLE
CWG2631 Immediate function evaluations in default arguments

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1312]
CWG2631

CWG, per its 2022-09-23 teleconference, seeks advice from EWG whether the drafted direction in the issue (delaying immediate invocations in default arguments to the point-of-call) is the intended design of the language.

**Comment by erichkeane** [comment]
EWG Discussed this at the [September 29, 2022 EWG Telecon](https://wiki.edg.com/bin/view/Wg21telecons2022/EWG-2022-09-29), and tool the following poll:

EWG Approves of the CWG Proposed resolution to CWG2631: 
| SF | F | N | A | SA |
|----|---|---|---|----|
| 12 | 4 | 0 | 0 |  0 |

Result: Consensus
