### ISSUE TITLE
CWG2518 Conformance requirements and #error/#warning

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1366]
CWG2518

C requires #error to cause rejection of the program.

This issue suggests we do likewise.

CWG solicits EWG review of the proposed direction.

**Comment by erichkeane** [comment]
EWG discussed this in the [February 6th, 2023](https://wiki.edg.com/bin/edit/Wg21issaquah2023/NotesEWGCWG2518) Afternoon session in Issaquah.

EWG agrees with the proposed resolution to CWG2518.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  4 | 15| 1 | 1 |  1 |

Result: Consensus

Additionally, this should be applied equally to failed static_assert.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  2 | 13| 2 | 1 |  1 |

Result: Consensus
