### ISSUE TITLE
CWG2521 User-defined literals and reserved identifiers 

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1367]
CWG2521

As explained in the issue, the normative rule does not give the outcome shown in the example. Even if it did, the significance of whitespace in this context is unfortunate.

CWG solicits EWG input on the handling of this issue.

**Comment by jensmaurer** [comment]
@erichkeane , a User Defined Literal never permits a space between the quotes (if any) and the name of the literal. This is only permitted when declaring a literal operator function as specified in [over.literal]. I am interpreting EWG's poll to refer to the latter, not the former.

**Comment by erichkeane** [comment]
That is a correct interpretation @jensmaurer. Discussion concentrated on the declarations, and I was apparently imprecise on the poll.  However, it was clear (via example) in the room what was meant.

**Comment by jensmaurer** [comment]
Some implementers are concerned about the lack of space for implementation extensions. The suggestion is to reserve literal suffix identifiers starting with two underscores for the implementation in 16.4.5.3.6 [[usrlit.suffix](https://wg21.link/usrlit.suffix)]. EWG is invited to comment on that direction.

CWG2521 has been updated accordingly.

**Comment by erichkeane** [comment]
EWG discussed this in the February 7th, 2023 Morning session in Issaquah. The following poll was taken.

CWG2521:
Suggest that LEWG amend the proposal for CWG2521 to reserve UDL declarations with double underscores anywhere for the implementation, then forward to CWG.

| SF | F | N | A | SA |
|----|---|---|---|----|
|  3 | 14| 5 | 3 |  0 |

Result: Consensus

**Comment by erichkeane** [comment]
@brycelelbach Attn!  This is LEWG's wording, so this has to go to through LEWG first.

**Comment by brycelelbach** [comment]
Okay we'll look.

**Comment by brycelelbach** [comment]
## 2023-02-07 15:30 to 17:30 Issaquah Library Evolution Meeting

[2023-02-07 15:30 to 17:30 UTC-8 Issaquah Library Evolution Minutes](http://wiki.edg.com/bin/view/Wg21kona2022/P2763#Library-Evolution-2023-02-07-15:30-17:30)

__Chair:__ Ben Craig (IP) & Billy Baker (IP)

__Minute Taker:__ Steve Downey (IP)

__POLL:__ Reserve literal suffix identifiers starting with two underscores for the implementation, as proposed in CWG2521

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|1|14|3|0|0|

__Attendance:__ 20 local, 8 remote

__# of Authors:__ 0

__Author Position:__ N/A

__Outcome:__ Consensus in favor

### Next Steps

Send CWG2521 to Core for C++23.

**Comment by brycelelbach** [comment]
@jensmaurer heads up.

**Comment by jfbastien** [comment]
The LEWG poll isn't aligned with the EWG poll, and this doesn't seem intentional. The feedback to CWG should be clear. LEWG, please explicitly poll the same as EWG, or poll explicitly to go against EWG's poll.

**Comment by ben-craig** [comment]
__POLL:__ Amend the proposed resolution for CWG2521 to reserve literal suffix identifiers with double underscores anywhere for implementation use (as recommended by EWG) then forward to CWG.

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|9|13|0|0|0|

__Attendance:__ many local 9 remote

__# of Authors:__

__Author Position:__

__Outcome:__ Unanimous consent

**Comment by jensmaurer** [comment]
@jwakely , @JeffGarland , the proposed resolution contains a one-sentence modification to a library clause. Please review CWG2521 (bottom).
