### ISSUE TITLE
LWG3810 CTAD for std::basic_format_args

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1368]
https://cplusplus.github.io/LWG/issue3810

LWG would like design guidance here. Should CTAD work? It's currently sort-of implied it should, but only if you assume that the exposition-only types and constructors are implemented exactly as shown. If the `format-arg-store`-type is defined as a nested type of `basic_format_args` (as in libstdc++) then it doesn't work.

There's an example from Tomasz in the issue showing a case where CTAD might be useful, but Victor suggested we should explicitly disable CTAD here, because it makes it easier to create dangling references.

**Comment by brycelelbach** [comment]
## 2023-01-10 Library Evolution Telecon

[LWG3810](https://wg21.link/LWG3810): CTAD for `basic_format_args`

[2023-01-10 Library Evolution Telecon Minutes](http://wiki.edg.com/bin/view/Wg21telecons2022/LWG3810#Library-Evolution-2023-01-10)

__Chair:__ Bryce Adelstein Lelbach

__Minute Taker:__ Ben Craig

__Start:__ 2023-01-10 11:58 Eastern

__POLL: Send the proposed resolution to LWG3810 (CTAD for `basic_format_args`) to Library for C++23, to be confirmed by a Library Evolution electronic poll.__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|0|8|0|0|0|

__Attendance:__ 13

__# of Authors:__ 0

__Author Position:__ N/A

__Outcome:__ Unanimous consensus in favor.

__End:__ 12:01

### Next Steps

Take a Library Evolution electronic poll to send the proposed resolution to LWG3810 (CTAD for `basic_format_args`) to Library for C++23.

**Comment by brycelelbach** [comment]
We only have two C++23 papers that need electronic polling, and both were non-controversial. I'm going to send this directly to Library.

**Comment by JeffGarland** [comment]
poll: approve the resolution for LWG3810 and move to immediate?

https://wiki.edg.com/bin/view/Wg21issaquah2023/LWG3810-202306

F | A | N
-- | -- | --
9 | 0 | 0

**Comment by frederick-vs-ja** [comment]
This should have been fixed by cplusplus/draft#6116.
