### ISSUE TITLE
CWG2543 constinit and optimized dynamic initialization

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1379]
See CWG2543

CWG seeks the advice of EWG how to proceed with this issue.

Subclause 9.2.7 [[dcl.constinit](https://wg21.link/dcl.constinit#2)] paragraph 2 states:

> If a variable declared with the constinit specifier has dynamic initialization (6.9.3.3 [[basic.start.dynamic](https://wg21.link/basic.start.dynamic)]), the program is ill-formed. [ Note: The constinit specifier ensures that the variable is initialized during static initialization (6.9.3.2 [[basic.start.static](https://wg21.link/basic.start.static)]). —end note] 

Subclause 6.9.3.2 [[basic.start.static](https://wg21.link/basic.start.static#3)] paragraph 3 gives permission for an implementation to perform static initialization in lieu of dynamic initialization:

> An implementation is permitted to perform the initialization of a variable with static or thread storage duration as a static initialization even if such initialization is not required to be done statically, provided that ... 

constinit will assuredly not give a diagnostic for variables that are constant initialized (7.7 [[expr.const](https://wg21.link/expr.const#2)] paragraph 2), because those are required to be statically initialized and thus will never be dynamically initialized. Conversely, constinit is guaranteed to give a diagnostic for variables that cannot be statically initialized, for example those with an initializer whose value depends on runtime conditions.

Between those boundaries, it is unclear whether constinit ought to give a diagnostic for variables whose initializer does not satisfy the constraints of constant-initialized, yet the implementation takes advantage of the permission to turn dynamic initialization into static initialization. For example,

```
  float f;
  constinit int * pi = (int*) &f;    // reinterpret_cast, not constant-initialized
```

The current wording seems to imply that constinit accurately reflects whether dynamic initialization was turned into static initialization by the implementation. However, that is impossible to implement, because such decisions are often made by the optimizer, which runs later than the compiler front-end interpreting the program text containing constinit.

There is value in permitting constinit not to diagnose some of the dynamic initializations that are turned into static initializations.

There is also value in having portable semantics of constinit.

**Comment by erichkeane** [comment]
This was discussed at the [Jan, 19, 2023 CWG Issues Review](https://wiki.edg.com/bin/view/Wg21telecons2023/EWG-2023-01-19-CWG-issues)

And the following poll was taken:

EWG Agrees that we want portable, guaranteed semantics for `constinit`
| SF | F | N | A | SA |
|----|---|---|---|----|
|  8 | 3 | 2 | 0 |  0 |

Result: Strong Consensus

EWG wishes to encourage further work in the direction of extending static initialization to more cases.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  1 | 5 | 6 | 1 |  0 |

Result: Not Consensus

**Comment by jensmaurer** [comment]
CWG 2023-02-06: Wording in CWG2543 approved by CWG; liaison discussion complete.
