### ISSUE TITLE
CWG2573 Undefined behavior when splicing results in a universal-character-name

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1405]
CWG solicits input from SG12 regarding addressing the undefined behavior in [lex.phases] p1.2

See CWG2573 for details.

**Comment by cor3ntin** [comment]
https://github.com/cplusplus/papers/issues/1283#issuecomment-1309073872

**Comment by cor3ntin** [comment]
P2621 was adopted

**Comment by jensmaurer** [comment]
@cor3ntin , please don't close these CWG-related issues. I also need to update the CWG issues list with the outcome. Feel free to assign them back to CWG.

**Comment by jensmaurer** [comment]
CWG2573 updated.
