### ISSUE TITLE
CWG2574 Undefined behavior when lexing unmatched quotes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1406]
CWG solicits input from SG12 regarding addressing the undefined behavior when lexing unmatched quotes.

See CWG2574 for details.

**Comment by cor3ntin** [comment]
see https://github.com/cplusplus/papers/issues/1283#issuecomment-1309073872

**Comment by frederick-vs-ja** [comment]
CWG2574 is also resolved by P2621.
