### ISSUE TITLE
LWG3840 filesystem::u8path should be undeprecated

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1415]
Undeprecating this API is evolutionary and so requires LEWG input:

https://cplusplus.github.io/LWG/issue3840

**Comment by brycelelbach** [comment]
Has SG16 seen this? @tahonermann?

**Comment by tahonermann** [comment]
> Has SG16 seen this?

@brycelelbach, no, but I don't think deprecation is really a SG16 concern. However, if you would like SG16 to offer a recommendation, I'll be happy to schedule a discussion there.

**Comment by brycelelbach** [comment]
## 2023-01-10 Library Evolution Telecon

[LWG3840](https://wg21.link/LWG3840): `filesystem::u8path` should be undeprecated

[2023-01-10 Library Evolution Telecon Minutes](http://wiki.edg.com/bin/view/Wg21telecons2022/LWG3840#Library-Evolution-2023-01-10)

__Chair:__ Bryce Adelstein Lelbach

__Minute Taker:__ Ben Craig

__Start:__ 2023-01-10 12:04 Eastern

__POLL: Send the proposed resolution to LWG3840 (`filesystem::u8path` should be undeprecated) to Library for C++23, to be confirmed by a Library Evolution electronic poll.__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|0|3|2|5|1|

__Attendance:__ 13

__# of Authors:__ 0

__Author Position:__ N/A

__Outcome:__ No consensus.

__End:__ 12:16

### Summary

This issue argues that we should undeprecate `filesystem::u8path`. We discussed this suggestion, but there was little appetite for doing so. It is easy to replicate the functionality in a few lines for those who need it.

### Next Steps

Close the issue.
