### ISSUE TITLE
CWG2678 std::source_location::current is unimplementable

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1416]
CWG alerts LWG and LEWG of serious implementability concerns when `std::source_location::current` appears in a constant expression in an inline function or in a function template.

See CWG2678 for details.

**Comment by brycelelbach** [comment]
@JeffGarland we'll take a first crack at this.

**Comment by billy-baker** [comment]
CWG2678 std::source_location::current is unimplementable

*Date:* 2023-02-06

*Attendance:*
   * 28 (room) + 12 (zoom)

__Champion:__ Richard Smith

__Chair:__ Billy Baker

__Minute Taker:__ Robert Leahy

__Start:__ 2023-02-06 16:00 Pacific

__POLL: Accessors should not be usable in constant expressions if the usage (e.g. within inline function, partial specializations, ...) could result in more than one definition (Richard's suggestion).__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|3|13|5|3|1|

__Attendance:__ 28 (room)  + 12

__# of Authors:__ 2

__Author Position:__ 2xSF

__Outcome:__ Consensus for not allowing access to members.

__End:__ 16:50

### Summary
LEWG agrees with the approach that Richard suggested in which the source_location member functions are not usable in a constant expression if the usage of current() could result in multiple definitions.

**Comment by brycelelbach** [comment]
@jfbastien please look at this for C++23.

**Comment by erichkeane** [comment]
EWG saw this in the [February 7th, 2023](https://wiki.edg.com/bin/view/Wg21issaquah2023/NotesEWGCWG2678) Morning Session, and the following poll was taken:

EWG approves of the approach for CWG2678 of changing the ODR to make use of source_location in a way that causes an inline function/function template/etc to 'be different' be an ODR violation (as proposed by Jason) as a DR.
| SF | F | N | A | SA |
|----|---|---|---|----|
| 16 | 19| 1 | 1 |  0 |

Result: Consensus

**Comment by erichkeane** [comment]
CWG has wording for what EWG wanted, so we don't have to see this again.

**Comment by jensmaurer** [comment]
CWG 2023-02-08: Approved the proposed resolution of CWG2678.
