### ISSUE TITLE
P2497 Testing for success or failure of <charconv> functions

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1454]
[P2497R0](https://wg21.link/p2497R0) Testing for success or failure of `<charconv>` functions (Jonathan Wakely)

**Comment by brycelelbach** [comment]
## 2023-02-06 10:30 to 12:00 Issaquah Library Evolution Meeting

[P2497R0](https://wg21.link/P2497R0): Testing for success or failure of `<charconv>` functions

[2023-02-06 10:30 to 12:00 UTC-8 Issaquah Library Evolution Minutes](http://wiki.edg.com/bin/view/Wg21kona2022/P2497#Library-Evolution-2023-02-06-10:30-12:00)

__Champion:__ Jonathan Wakely (R)

__Chair:__ Bryce Adelstein Lelbach (IP) & Ben Craig (IP)

__Minute Taker:__ Steve Downey (IP)

__Start:__ 2023-02-06 11:17 UTC-8

Does this paper have:
   * Examples?
      * Yes.
   * Field experience?
      * No.
   * Performance considerations?
      * N/A
   * Discussion of prior art?
      * Yes.
   * Changes Library Evolution previously requested?
      * Yes.
   * Wording?
      * Yes.
   * Breaking changes?
      * No.
   * Feature test macro?
      * Yes.
   * Freestanding?
      * Yes.

__POLL: Add an explicit bool conversion to `to_chars_result` and `from_chars_result` that returns true if the operation was successful.__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|3|15|1|3|0|

__Attendance:__ 22 (in person) + 9 (remote)

__# of Authors:__ 0

__Author Position:__ N/A

__Outcome:__ Consensus in favor.

__POLL: Add a named member function to `to_chars_result` and `from_chars_result`that returns true if the operation was successful.__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|1|7|8|5|0|

__Attendance:__ 22 (in person) + 9 (remote)

__# of Authors:__ 0

__Author Position:__ N/A

__Outcome:__ No consensus.

__POLL: Send P2497R0 (Testing for success or failure of `<charconv>` functions) to Library for C++23 as the resolution to C++23 National Body comment GB-083, classified as B2 - improvement.__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|6|12|2|2|0|

__Attendance:__ 22 (in person) + 10 (remote)

__# of Authors:__ 1

__Author Position:__ SF

__Outcome:__ Consensus in favor.

WA: Error types in if statements with explicit functions that state whether an error occured is more readable that bool conversions.

__End:__ 11:38

### Summary

This paper improves usability enhancements to `<charconv>`s error handling mechanism. Originally, adding `operator!` to `errc` was suggested. Library Evolution instead requested in our last review that an explicit bool conversion operator be added to `(to|from)_chars_result`, although this does not help when you are destructuring those types. During this review, some expressed a concern with an explicit boolean conversion, because in some contexts true might mean an error occurred and in others true might mean that an error did not occur. Those individuals advocated for some form of explicitly named function or member. However, we had the strongest consensus for adding an explicit bool conversion to `(to|from)_chars_result`.

### Next Steps

Send P2497R0 (Testing for success or failure of `<charconv>` functions) to Library for C++23 as the resolution to C++23 National Body comment GB-083, classified as B2 - improvement.

**Comment by brycelelbach** [comment]
@JeffGarland heads up, C++23.

**Comment by JeffGarland** [comment]
https://wiki.edg.com/bin/view/Wg21issaquah2023/P2497R0-202306

poll: put P2497r0 into C++23?


F | A | N
-- | -- | --
8 | 0 | 0
