### ISSUE TITLE
CWG2692 Static and explicit object member functions with the same parameter-type-lists

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1455]
Consider this example:

```
  struct A {
    static void f(A);
    void f(this A);

    void g();
  };

  void A::g() {
    (&A::f)(A()); // #1
    (&A::f)();    // #2
  }
```

What should happen for #1? One possible answer is that the /member-specification/ of `A` is ill-formed because of conflicting declarations for `f`. That would also allow mangling the explicit-object member function `A::f` the same as the static member function.

See CWG2692

**Comment by erichkeane** [comment]
This was discussed in the [February 6th, 2023 ](https://wiki.edg.com/bin/view/Wg21issaquah2023/NotesEWGCWG2692)afternoon session in Issaquah.

No polls were taken, however Gašper has agreed to work with Barry to return with a paper exploring the design space, and propose a solution.

**Comment by erichkeane** [comment]
This was discussed in the[ February 8th, 2023](https://wiki.edg.com/bin/view/Wg21issaquah2023/NotesEWGCWG2692) afternoon session in Issaquah.  The following polls were taken:

Given:
```
struct A {
  static void f(A); // #A
  void f(this A);   // #B

  static void e(A const&); // #C
  void e() const&;         // #D

  void g() {
    // static + explicit memfn
    (&A::f)(A()); // #1
    f(A());       // #2
    (&A::f)();    // #3

    // static + implicit memfn
    (&A::e)(A()); // #4
    e(A());       // #5
    (&A::e)();    // #6
  }
};
```


#1 == #2, and #4 == #5
| SF | F | N | A | SA |
|----|---|---|---|----|
|  0 | 0 | 2 | 9 |  1 |

Result: Consensus Against


#1 is ambiguous, #2 calls '#A'
#4 is ambiguous, #5 calls '#C'
| SF | F | N | A | SA |
|----|---|---|---|----|
|  5 | 7 | 0 | 0 |  0 |

Result: Consensus

Authors will work with their core expert and bring this directly to CWG.

**Comment by jensmaurer** [comment]
Resolved by P2797R0.
