### ISSUE TITLE
CWG2697 Deduction guides using abbreviated function syntax

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1465]
It is unclear whether deduction guides are intended to be expressible using abbreviated function syntax. 

See CWG2697 for details.

CWG solicits EWG design guidance in that matter.

**Comment by raidenluikang** [comment]
If you want fame, come up with useful things, and don't save someone else's links.

**Comment by erichkeane** [comment]
EWG discussed this during the [May 11th, 2023](https://wiki.edg.com/bin/view/Wg21telecons2023/EWG-2023-05-11) telecon, and the following poll was taken:

For CWG2697, CWG should clarify that Abbreviated Function Syntax should not be permitted in deduction guides (without prejudice against a future proposal to give concrete meaning to this syntax).

| SF | F | N | A | SA |
|----|---|---|---|----|
|  4 | 6 | 2 | 0 |  0 |

Result: Consensus

This should provide sufficient feedback for CWG to clarify our intent, so reassigning to CWG.
