### ISSUE TITLE
CWG2698 Using extended integer types with z suffix

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1467]
It appears the approved wording allows using extended integer types for integer literals with a "z" suffix. The author of the paper introducing the feature claims that was not intended, yet the paper introducing the feature seems silent on the issue.

CWG seeks approval of EWG for restricting z and Z suffixes to `std::size_t` and its corresponding signed integer type.

See CWG2698 for details.

**Comment by erichkeane** [comment]
EWG discussed this during the [May 11th, 2023](https://wiki.edg.com/bin/view/Wg21telecons2023/EWG-2023-05-11) telecon, and the following poll was taken:

For CWG2698, EWG accepts the CWG proposed resolution, which clarifies that the 'z'/'zu' suffix means "the signed type corresponding to size_t"/size_t only.

| SF | F | N | A | SA |
|----|---|---|---|----|
|  6 | 8 | 0 | 0 |  0 |

Result: Consensus


Sufficient guidance was given to unblock CWG, so assigning back to CWG.

**Comment by cklim4405** [comment]
> It appears the approved wording allows using extended integer types for integer literals with a "z" suffix. The author of the paper introducing the feature claims that was not intended, yet the paper introducing the feature seems silent on the issue.
> 
> CWG seeks approval of EWG for restricting z and Z suffixes to `std::size_t` and its corresponding signed integer type.
> 
> See CWG2698 for details.
