### ISSUE TITLE
p0323r7 avoid explicit throw an exception, including bad_access_expected

### ISSUE THREAD

**Issue by raidenluikang** [cplusplus/papers#1493]
Is [p0323r7](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0323r7.html) adopted by c++23 ?

`std::expected` very good candidate for alternative exceptions error-code principle. But there access `value` methods throw the exception `bad_access_expected`: again the exception!   `std::expected`  already have `has_value` method to check this situation.

 Yes, `std::optional::value()` also throws exception, but `std::expected` specially class for  exception-free code, in my opinion.

I personally thought about, why can't to remove explicit  throwing any exception ?

For example, std::move_only_function's call "empty" state no more throws bad_functional_call exception, it simply cause an UB.

Pls, remove bad_access_expected class, and  do not  throw an any exception, explicitly!  Let `value()` cause an UB, if there `error` state.

**Comment by Dani-Hub** [comment]
This is not the right place to discuss design changes.

**Comment by raidenluikang** [comment]
Do me a favor! Can you share right place link?

**Comment by Dani-Hub** [comment]
There exists no specific link for this, it depends very much on your own involvement. 

If you want to "just" discuss it, open a discussion in https://lists.isocpp.org/mailman/listinfo.cgi/std-discussion

You can write a proposal involving a design change and argue about that. How to do that is described here: https://isocpp.org/std/submit-a-proposal
But before writing a proposal, I recommend starting with the [std-discussion] reflector.

**Comment by frederick-vs-ja** [comment]
The adopted revision is [P0323R12](https://wg21.link/p0323r12). See #254.

**Comment by jensmaurer** [comment]
This issue tracker is for administratively tracking WG21 papers, not for general discussion about C++. Please use the search functionality to determine the status of existing papers.
