### ISSUE TITLE
P1228 A proposal to add an efficient string concatenation routine to the Standard Library

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#151]
[P1228R1](https://wg21.link/p1228r1) A proposal to add an efficient string concatenation routine to the Standard Library (Jorg Brown)

See also [P1479](https://wg21.link/p1479) ostringstream wrapper #235.

**Comment by tahonermann** [comment]
SG16 reviewed this paper at our February 13th, 2019 telecon.  Meeting notes are available at https://github.com/sg16-unicode/sg16-meetings#february-13th-2019

We conducted one poll to give guidance to the author.

Poll: Do we want to restrict arguments to strings, characters, and types convertible to strings?
```
SF  F  N  A SA
 3  4  1  0  1
```
Chair's poll interpretation: SG16 advises restricting concatenation to string and character types initially with the option to add support for numeric and other types later.  The chair advises caution regarding these poll results; the SA vote reflects the author's well-informed long term experience with the feature.

Removing the SG16 label.

**Comment by brycelelbach** [comment]
[Discussed at the Kona 2019 meeting by LEWGI](http://wiki.edg.com/bin/view/Wg21kona2019/StringConcatenation)

P1479R0 ostringstream wrapper

__Champion:__ Mike Spertus

__Minute Taker:__ Ben Craig

__Start Overview:__ 16:00

__End:__ 16:17

P1228R1 std::concat

__Champion:__ Jorg Brown

__Minute Taker:__ Ben Craig

__Start Overview:__ 16:17

__Start Polling:__ 16:45

__POLL: We should promise more committee time to pursuing P1479R0 ostringstream wrapper, knowing that our time is scarce and this will leave less time for other work.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|0|1|8|6|1|

__Attendance:__ 17

That has no consensus.

Peter Bindels (SA): Easy to do yourself, not sure it’s a good use of time.

__POLL: We should promise more committee time to pursuing P1228R1 efficient string concatenation, knowing that our time is scarce and this will leave less time for other work.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|2|9|3|2|0|

__Attendance:__ 17

That has consensus.

Peter Bindels (A): Not sure this is a good fit for `std::`, use case may be too niche.

Bryce (A): Too many of these things; feel like fmt is good enough, and constexpr fmt may be a thing in the future.

__POLL: We want to see a revision of P1228R1 that just concatenates things currently convertible to string_view and chars.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|0|5|4|2|3|

__Attendance:__ 15

That has no consensus.

__End:__ 17:00

__CONSENSUS: We will not pursue P1479R0.__

__CONSENSUS: Bring a revision of P1228R1 to LEWGI for further design review.__

---+++ LEWGI Thursday Morning After Break: Direction Review (Compile Time `std::format`)

__Champion:__ Hana Dusikova

__Minute Taker:__ Timur Doumler

**Comment by cor3ntin** [comment]
I tried to contact the author, in the absence of updates, and reply, I'm closing this issue.
We will reopen it if a new version of the paper is published.
