### ISSUE TITLE
P2892 R0 std::simd Types Should be Regular

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1513]
[P2892R0](https://wg21.link/P2892R0) std::simd Types Should be Regular (Joe Jevnik, David Sankel)

**Comment by inbal2l** [comment]
## 2023-06-13 Library Evolution Varna

[P2892R0](https://wg21.link/P2892R0): std::simd Types Should be Regular

[2023-06-13 Library Evolution Minutes](http://wiki.edg.com/bin/view/Wg21varna/P2892#Library-Evolution-2023-06-13-Morning-Session-1)

__Champion:__ David Sankel

__Chair:__ Bryce Adelstein Lelbach, Fabio Fracassi

__Minute Taker:__ Inbal Levi

### Summary

TODO: @brycelelbach

### Next Steps

TODO: @brycelelbach

**Comment by inbal2l** [comment]
The change suggested in the paper was not supported. The authors will re-battle this discussion in a separate paper.
