### ISSUE TITLE
P2855 R1 Member customization points for Senders and Receivers

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1518]
[P2855R0](https://wg21.link/P2855R0) Member customization points for Senders and Receivers (Ville Voutilainen)

**Comment by inbal2l** [comment]
## 2023-06-12 Library Evolution Varna

[P2855R0](https://wg21.link/P2855R0): Member customization points for Senders and Receivers

[2023-06-12 Library Evolution Minutes](http://wiki.edg.com/bin/view/Wg21varna/P2855#Library-Evolution-2023-06-12-Morning-Session-2)

__Champion:__ Ville Voutilainen

__Chair:__ Fabio Fracassi, Nevin Liber

__Minute Taker:__ Nat Goodspeed

### Summary

TODO: @FabioFracassi

### Next Steps

TODO: @FabioFracassi

**Comment by inbal2l** [comment]
## 2023-11-06 Library Evolution Varna

[P2855R0](https://wg21.link/P2855R0): Member customization points for Senders and Receivers

[2023-11-06 Library Evolution Minutes](https://wiki.edg.com/bin/view/Wg21kona2023/P2855#Library-Evolution-2023-11-06)

Was seen as a reference to the work done to reduce "tag_invoke". No progress was made on the paper.

**Comment by ben-craig** [comment]
## 2024-03-20 Library Evolution Tokyo

[P2855R1](https://wg21.link/P2855R1): Member customization points for Senders and Receivers

[2024-03-20 Library Evolution Tokyo Minutes](https://wiki.edg.com/bin/view/Wg21tokyo2024/P2855#Library_Evolution_Telecon_2024-03-20)

__Champion:__ Ville Voutillainen
__Chair:__ Ben Craig / Inbal Levi
__Minute Taker:__ Guy Davidson

### Summary

__POLL: Send P2855R1 (Member customization points for Senders and Receivers) to LWG for C++26 classified as B1, to be merged into P2300, to be confirmed with a Library Evolution electronic poll.__

|SF|WF|N|WA|SA|
|-|-|-|-|-|
|12|5|2|0|0|

__Attendance:__ 16+5

__# of Authors:__ 1

__Author Position:__ SF

__Outcome:__ Strong Consensus

__Comments:__
WF: SF if there was more impl experience


__POLL: Remove receiver_adaptor ([exec.utils.rcvr.adptr]) and related tag invoke overloads ([exec.utils.rcvr.adptr.nonmembers]) from P2300, pending electronic polling results.__

|SF|WF|N|WA|SA|
|-|-|-|-|-|
|15|2|0|0|0|

__Attendance:__ 16+5

__# of Authors:__ ???

__Author Position:__

__Outcome:__ Strong Consensus

__Comments:__

### Next Steps

Electronic polling and merging with P2300.

**Comment by inbal2l** [comment]
[P2855R0](https://wg21.link/P2855R1) was added to 2024 February LEWG electronic poll paper ([P3213R0](https://wg21.link/P3213R0))

**Comment by inbal2l** [comment]
Applying [P2855R1](https://wg21.link/P2855R1) on P2300 was approved by LEWG on LEWG 2024 April electronic poll ([P3214R0](https://wg21.link/P3214R0))

**Comment by inbal2l** [comment]
@jwakely, @JeffGarland - IIRC the paper was applied to P2300 in 2024-Tokyo meeting, correct? If so, please close it.

**Comment by ben-craig** [comment]
Merged into P2300R10, and approved in plenary.
