### ISSUE TITLE
P2857 P2596 Critique

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1519]
[P2857R0](https://wg21.link/P2857R0) P2596 Critique (Matthew Bentley)

**Comment by brycelelbach** [comment]
Related to P0447 (#328) and P2596 (#1256).

**Comment by inbal2l** [comment]
## 2023-02-07 15:30 to 17:30 Issaquah Library Evolution Meeting

Discussed alongside other papers, see: https://github.com/cplusplus/papers/issues/1256

[Full Minutes](http://wiki.edg.com/bin/view/Wg21issaquah2023/P0447#Library-Evolution-2023-02-07-15:30-17:30)

[P0447R21](https://wg21.link/P0447R21): Introduction of `std::hive` to the standard library
[P2596R0](https://wg21.link/P2596R0): Improve `std::hive::reshape`
[P2857R0](https://wg21.link/P2857R0): Rebuttal to P2596

__Champion:__ Guy Davidson (P0447, P2857) & Patrice Roy (P2596)

__Chair:__ Ben Craig

__Minute Taker:__ Steve Downey

__Start:__ 2023-02-07 15:45 UTC-8

Does this paper have:
   * Examples? Yes
   * Field experience? Yes
      * Implementation experience? Yes
      * Usage experience? Yes
      * Deployment experience? Yes
   * Performance considerations? Yes
   * Discussion of prior art? Yes
   * Changes Library Evolution previously requested? Yes
   * Wording? Yes
   * Breaking changes? No
   * Feature test macro? Yes
   * Freestanding? No
   * Format and/or iostream support? No

__End:__ 17:10

### Summary

We started with covering the revisions made to the paper.  We then discussed P2596, which proposes modifications to std::hive.  We looked at that wording, then heard a rebuttal of P2596.  There were continued questions about whether we should be spending time on std::hive.

While there is field usage and deployment experience, there were concerns that this paper isn't providing enough evidence of existing practice in the field.

__POLL:__ We like P2596 "Improve std::hive::reshape" enough to go through the wording

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|4|11|4|2|2|

__Attendance:__ 20 local, 12 remote

__# of Authors:__ 1

__Author Position:__ SF

__Outcome:__ consensus

A: I think reshape is useful, but I don't have concrete arguments
SA: Not convinced we should spend more time on this at all

__POLL:__ Spend more committee time on std::hive

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|8|4|5|2|3|

__Attendance:__ 22 local, 11 remote

__# of Authors:__ 2

__Author Position:__ 2xSF?

__Outcome:__ Not enough enough consensus to stop

__POLL:__ Apply P2596 (Improve std::hive::reshape) to P0447R21 (Introduction of std::hive to the standard library) and return to LEWG

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|2|3|8|4|3|

__Attendance:__ 27 local, 10 remote

__# of Authors:__

__Author Position:__

__Outcome:__ No consensus to change.  1 meeting for rebuttal to the rebuttal

### Next Steps

There wasn't a consensus to change the hive paper. We encourage the authors to work together to resolve the conflicts.  The author of P2596 has one meeting to provide a rebuttal to the rebuttal before we attempt to move forward with P0447.
