### ISSUE TITLE
P2861 The Lakos Rule: Narrow Contracts And `noexcept` Are Inherently Incompatible

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1520]
[P2861R0](https://wg21.link/P2861R0) The Lakos Rule: Narrow Contracts And `noexcept` Are Inherently Incompatible (John Lakos)

**Comment by inbal2l** [comment]
Superseded by P3155, and will be considered as part of the same discussion.

**Comment by inbal2l** [comment]
Superseded by [P3155](https://wg21.link/P3155), and will be considered as part of the same discussion.
