### ISSUE TITLE
P2867 R1 Remove Deprecated strstreams From C++26

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1523]
[P2867R0](https://wg21.link/P2867R0) Remove Deprecated strstreams From C++26 (Alisdair Meredith)

**Comment by cor3ntin** [comment]
A mailing list review was held the week of the 2nd October 2023. https://lists.isocpp.org/lib-ext/2023/10/25805.php
We took a poll to forward this to electronic polling.

With 19 votes in favor, including some implementers support and no objection or further comments, the vote pass, and this will be forwarded to LWG after electronic polling.

**Comment by inbal2l** [comment]
[P2867R1](https://wg21.link/P2867R1) was added to LEWG 2023 December electronic poll paper ([P3053R0](https://wg21.link/P3053R0))

**Comment by inbal2l** [comment]
[P2867R1](https://wg21.link/p2867r1) was forwarded to LWG on LEWG 2023 December electronic poll ([P3054R0](https://wg21.link/P3054R0))
