### ISSUE TITLE
P2895 noncopyable and nonmoveable utility classes

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1534]
[P2895R0](https://wg21.link/P2895R0) noncopyable and nonmoveable utility classes (Sebastian Theophil, Jonathan Müller)

**Comment by cor3ntin** [comment]
Mailing list outcome: 

There was a strong consensus than deleting the constructors was a more correct, equally convenient approach.
These classes, if used, would increase the size of some classes in the case of multiple inheritance, so they are not a replacement for existing facility.

LEWG also observed that if one prefers that mechanism over deleting members, it is easy to implement them in a code base, which does not need to be the standard library. 

This paper then had a strong sentiment against. We are going to close it.
If the authors want to pursue this further with stringer motivation , they are of course feel free to do so, but we would in that case probably prefer discuss the paper in LEWGI.
