### ISSUE TITLE
P1302 Implicit Module Partition Lookup

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#155]
[P1302R1](https://wg21.link/p1302r1) Implicit Module Partition Lookup (Isabella Muerte, Richard Smith)

**Comment by jensmaurer** [comment]
[EWG in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1302R1-EWG)

**Comment by brycelelbach** [comment]
[Cologne 2019-07 LEWGI Minutes](http://wiki.edg.com/bin/view/Wg21cologne2019/P1302)

[P1302R2](https://wg21.link/P1302R2) Implicit Module Partition Lookup

__Champion:__ Richard Smith

__Minute Taker:__ Mark Zeven

__Start Overview:__ 07-19 16:47

__Start Review:__ 16:51

__Start Polling:__ 17:09

__POLL: Pursue recommendations for implicit builds of modules in the C++ Modules Ecosystem Technical Report.___

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|3|6|7|2|0|

__Attendance:__ 19

That has weak consensus.

__POLL: Pursue a recommended implicit module partition lookup scheme for the C++ Modules Ecosystem Technical Report.___

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|2|3|8|2|0|

__Attendance:__ 17

That does not have consensus.

__End:__ 17:15

__CONSENSUS: In the C++ Modules Ecosystem Technical Report, we want recommendations for implicit builds of modules which do not prescribe a particular file layout or file naming scheme.__
