### ISSUE TITLE
CWG2560 Parameter type determination in a requirement-parameter-list

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1582]
The question is whether parameters for a _requires-expression_ enjoy the same array-to-pointer and function-to-pointer conversions as function parameter types.

There are arguments for both choices.

See CWG2560 for details.

**Comment by erichkeane** [comment]
EWG discussed [CWG2560](https://cplusplus.github.io/CWG/issues/2560.html) during the [Tuesday Morning session](https://wiki.edg.com/bin/view/Wg21kona2023/NotesEWGCWG2560) in Kona.  The following poll was taken.

CWG2560 "Parameter type determination in a requirement-parameter-list" accept the proposed resolution, forward to CWG for inclusion in C++26, and treat it as a Defect Report on previous versions.
| SF | F | N | A | SA |
|------|---|-----|---|------|
|  3  |14 |  3  | 1|   0   |

Result: Consensus

**Comment by jensmaurer** [comment]
CWG 2023-11-07: Approved; to be moved in Tokyo.
