### ISSUE TITLE
CWG2751 Order of destruction for parameters for operator functions

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1583]
In an ABI with callee-cleanup, the following causes implementation hardship because the order of construction of the parameters for the two overloaded operators is required to be different, causing conflicting requirements on the order of parameter destruction.

```
  void operator<<(A, B);
  void operator+=(A, B);
  void (*p)(A, B) = cond ? &operator<< : &operator+=;
```

See CWG2751 for details.

**Comment by erichkeane** [comment]
EWG discussed [CWG2751](https://cplusplus.github.io/CWG/issues/2751.html) during the [Tuesday Morning session](https://wiki.edg.com/bin/view/Wg21kona2023/NotesEWGCWG2751) in Kona.  The following poll was taken.

CWG2751 "Order of destruction for parameters for operator functions" not a defect, the proposed implementation strategy can be picked if the implementation so desires.
| SF | F | N | A | SA |
|------|---|-----|---|------|
|  6  |  6 |  4 |  0 |   0   |

Result: Consensus
