### ISSUE TITLE
CWG2733 Applying [[maybe_unused]] to a label 

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1585]
Both gcc and clang accept [[maybe_unused]] on an identifier label.

This seems to be a small extension that improves consistency of the language; EWG is asked to approve.

See CWG2733 for details including CWG-approved wording.

**Comment by erichkeane** [comment]
EWG discussed [CWG2733](https://cplusplus.github.io/CWG/issues/2733.html) during the [Tuesday Morning session](https://wiki.edg.com/bin/view/Wg21kona2023/NotesEWGCWG2733) in Kona.  The following poll was taken.

CWG2733 "Applying [[maybe_unused]] to a label" accept the proposed resolution, forward to CWG for inclusion in C++26.
| SF | F | N | A | SA |
|------|---|-----|---|------|
|  5  | 12|  3  | 0  |    0  |

Result: Consensus

**Comment by jensmaurer** [comment]
CWG 2023-11-07: Approved.
