### ISSUE TITLE
CWG2548 Array prvalues and additive operators

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1633]
CWG seeks advice from EWG whether support for array prvalue operands should be added for the indirection operator, the unary + operator, and the additive operators, along the lines of the wording in the issue. Similar to the [] operator, the specification of the indirection operation could be amended to yield an xvalue if the argument is a prvalue.

See CWG2548 for details.

**Comment by erichkeane** [comment]
EWG discussed [CWG2548](https://cplusplus.github.io/CWG/issues/2548.html) during the [Tuesday Morning session](https://wiki.edg.com/bin/view/Wg21kona2023/NotesEWGCWG2548) in Kona.  The following poll was taken.

CWG2548 "Array prvalues and additive operators" is not a defect, this corner-case should not be supported given the direction given to P2865.
| SF | F | N | A | SA |
|------|---|-----|---|------|
|  4  |  7  | 5  | 3  |  0    |

Result: Consensus

**Comment by tkoeppe** [comment]
Feedback from @zygoloid:

"CWG seeks advice from EWG whether support for array prvalue operands should be added for the indirection operator, the unary + operator, and the additive operators, along the lines of the wording above. Similar to the [] operator, the specification of the indirection operation could be amended to yield an xvalue if the argument is a prvalue. The unary + operator is occasionally used to force an array-to-pointer decay." -- sounds like CWG was asking for yes or no, not a fishing expedition.

CWG found three places where array prvalues didn't work, but array glvalues did, and wanted permission to make them work. And had wording changes to do so.

I think the reference to P2865 was a distraction; the CWG issue was about making prvalues decay in the same places where glvalues do (where there was a wording oversight preventing decay but implementations mostly did it anyway). P2865 was about not allowing arrays at all as operands of some operators.

**Comment by jfbastien** [comment]
EWG re-discussed given the above feedback. The issue might have been inadvertent but EWG likes the omission even if it is inconsistent. Adding the features for consistency does not seem useful, hence the resolution of "not a defect". That said, EWG could be convinced if a paper were presented to add the feature with compelling motivation.
