### ISSUE TITLE
CWG2561 Conversion to function pointer for lambda with explicit object parameter

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1689]
It's unclear what's supposed to happen here.

See CWG2561 for details.

CWG is requesting guidance from EWG.

**Comment by erichkeane** [comment]
EWG discussed [CWG2561](https://cplusplus.github.io/CWG/issues/2561.html) during the [Tuesday morning session](https://wiki.edg.com/bin/view/Wg21kona2023/NotesEWGCWG2561) in Kona.  The following poll was taken.

CWG2561 "Conversion to function pointer for lambda with explicit object parameter" we would like to move forward with option #1 "punt" from D3031, forwarding to CWG for C++26.  A subsequent paper can explore other solutions.

|SF|F|N|A|SA|
|-|-|-|-|-|
|9|11|3|0|0|

Result: Consensus

**Comment by jensmaurer** [comment]
CWG 2023-11-09: Reviewed; keeping in "review" status in anticipation of a paper proposing reasonable semantics for the function pointer conversion.

**Comment by jensmaurer** [comment]
The related paper is tracked via #1711.
