### ISSUE TITLE
LWG3971 Join ranges of rvalue references with ranges of prvalues

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1690]
LWG would like SG9 to consider this issue:
https://cplusplus.github.io/LWG/issue3971

**Comment by jwakely** [comment]
Yes please

**Comment by foonathan** [comment]
SG 9 discussed it in Tokyo on Tuesday morning: https://wiki.edg.com/bin/view/Wg21tokyo2024/NotesSG9LWG3971

Poll: SG9 believe that LWG3971 is a use-after-move and is working as intended. We further believe that matching the behavior of concat_view (which is the current behavior) is important. This is not a defect.

| SF | F | N | A | SA |
|----|---|---|---|----|
| 3  | 3 | 0 | 0 | 0  |

Attendance: 11
Outcome: Unanimous consent.
