### ISSUE TITLE
LWG 3988: Should as_const_view and basic_const_iterator provide base()?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1691]
LWG would like SG9 to take a look at this issue:
https://cplusplus.github.io/LWG/issue3988

**Comment by dhollman** [comment]
SG9 voted on the following poll in Kona:

Forward the proposed changes in LWG3988 to LWG as a DR on C++23 (without a paper)

SF | F | N | A | SA
-- | -- | -- | -- | --
2 | 5 | 1 | 1 | 0

(This should probably be "to LEWG", but we weren't sure whether we officially forward issues to LWG or. LEWG).

**Comment by jwakely** [comment]
Thanks. Let's ask lewg to confirm the sg9 decision before sending it back to lwg.

**Comment by ben-craig** [comment]
## 2024-02-20 Library Evolution Telecon

[LWG3988](https://wg21.link/LWG3988): Should as_const_view and basic_const_iterator provide base()?

[2024-02-20 Library Evolution Telecon Minutes](https://wiki.edg.com/bin/view/Wg21telecons2024/LWG3988#Library_Evolution_Telecon_2024-02-20)

__Champion:__ Hewill Kang
__Chair:__ Ben Craig
__Minute Taker:__ Eddie Nolan


### Summary

__POLL: Send a paper with the changes proposed in LWG3988 (Should as_const_view and basic_const_iterator provide base()?) to LWG as a defect report for C++23, to be confirmed with a Library Evolution electronic poll.  Motivation, rationale, and impact of the changes will be audited by Arthur O'Dwyer, Ben Craig, and Inbal Levi (optional Alisdair Meredith).__

|SF|WF|N|WA|SA|
|-|-|-|-|-|
|2|3|4|5|4|

__Attendance:__ 19

__# of Authors:__ 1

__Author Position:__ SF

__Outcome:__ No consensus for change

__Comments:__ 


### Next Steps

Closing the issue, with no consensus for change

**Comment by jwakely** [comment]
LWG actually looked at this in Kona after SG9 discussed it, and voted to move the issue to Ready (F:8 N:0 A:1). But I think in light of today's LEWG decision, that LWG decision should be revisited.
