### ISSUE TITLE
CWG2825 Range-based for statement using a braced-init-list

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1694]
In a range-based for, `std::initalizer` should use its member functions, not the free functions affected by argument-dependent lookup.

See CWG2825 for details.

**Comment by erichkeane** [comment]
CWG2825 "Range-based for statement using a braced-init-list" accept the resolution as proposed, forward to CWG for C++26, apply as a DR.

| SF | F  | N  | A  | SA |
|----|----|----|----|----|
|  5 |  6 |  2 |  0 |  0 |

Result: Consensus
