### ISSUE TITLE
 P2977 R0 Module configuration files

### ISSUE THREAD

**Issue by mathstuf** [cplusplus/papers#1697]
[P2977R0](https://wg21.link/p2977r0) Module configuration files (Ben Boeckel)

**Comment by c0nstexpr** [comment]
seems to be [D2977R0](https://isocpp.org/files/papers/D2977R0.html)

> the proposal's link is broken :(

**Comment by mathstuf** [comment]
Published. Now available at the main link.

**Comment by jfbastien** [comment]
https://github.com/cplusplus/papers/issues/1702
