### ISSUE TITLE
CWG2819 Cast from null pointer value in a constant expression

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1698]
The issue asks to support conversions from `void*` to a pointer-to-object type also when the original pointer is a null pointer value.

CWG seeks approval from EWG for the design direction.

See CWG2819 for details.

**Comment by erichkeane** [comment]
EWG discussed this during the [Monday AM](https://wiki.edg.com/bin/view/Wg21tokyo2024/NotesEWGCWG2819) session on Tokyo.  The following poll was taken:

For CWG2819, EWG agrees with the proposed resolution, send back to CWG for inclusion in C++26.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  12  |13 | 0 |  0 |  0 |

Result:Consensus
