### ISSUE TITLE
CWG2836 Conversion rank of long double and extended floating-point types

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1699]
A case was found where the outcome of the C++ implicit conversions is not aligned with the outcome of C, despite P1467's documented goal.

One of the authors of P1467 asserts the deviation from C is intentional.

CWG asks EWG to confirm, thus closing CWG2836 as NAD.

**Comment by jfbastien** [comment]
From Jim Thomas:

> This particular issue was discussed at the 2021-12-22 CFP meeting. The following is extracted from the meeting minutes ([N2910](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2910.pdf)):
> 
> 7) [2302] C++ liaison issue from David Olsen
>  Relates to arith conversions occurring between long double and _Float64.
>  David Olsen says an expression converting to long double is more consistent.
>  But, the current draft says that such an expression converts to _Float64.
>  It was noted that a standard type may have lesser quality arithmetic than
>  an interchange type which is at odds with the fact that we really want to
>  lean towards better quality arithmetic
>  Jim proposed some text if we decide to change.
>  It was also noted that such a change also
>  * affects tgmath rules for which examples need to be checked, and
>  * adds another special case to an already complicated set of rules.
>  Motivated by Microsoft Visual C++ where long double is the same as double.
> 
> Conclusion: Recommend no change - change does not justify added complexity.
>

**Comment by NinaRanns** [comment]
From the email thread : "Given the rationale linked above, the previous SG22 discussion and related polls recorded in [WG14 N2835](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2835.pdf), and the subsequent reconfirmation by the WG14 CFP SG recorded in [WG14 N2910](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2910.pdf), I no longer see a reason for SG22 to discuss this CWG issue. I agree with the direction currently indicated in the CWG issue to add an annex C entry."

**Comment by erichkeane** [comment]
EWG discussed this during the [Monday AM](https://wiki.edg.com/bin/view/Wg21tokyo2024/NotesEWGCWG2836) session in Tokyo.  No poll was taken, but we expect to see this again later in the week after offline discussions.

**Comment by hanickadot** [comment]
Close CWG2836 as not a defect.

|SF| F| N| A|SA|
|--|--|--|--|--|
|3|10|3|0|1|

Consensus
