### ISSUE TITLE
P1395 Modules: Partitions Are Not a Panacea

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#187]
[P1395R0](https://wg21.link/p1395r0) Modules: Partitions Are Not a Panacea (Nathan Sidwell)

**Comment by jensmaurer** [comment]
[EWG in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1395R0-EWG)

**Comment by villevoutilainen** [comment]
Superseded by https://github.com/cplusplus/papers/issues/377
