### ISSUE TITLE
P3285 R0 Contracts Protecting The Protector

### ISSUE THREAD

**Issue by rogerorr** [cplusplus/papers#1897]
[P3285R0](https://wg21.link/p3285r0) Contracts: Protecting The Protector (Gabriel Dos Reis)

**Comment by rogerorr** [comment]
The author presented P3285R0 to SG23 in a 2024-05-20 Zoom session.
The following polls were taken:

__POLL: We should promise more SG23 committee time to pursuing the approach of handling certain kinds of undefined behaviour differently inside and outside of contract predicates, knowing that our time is scarce and this will leave less time for other work.__

|Favor|Neutral|Against|
|-|-|-|
|7|3|13|

__POLL: The P2900 treatment of undefined behaviour inside contract predicates is adequate for progress towards publication in an IS or TS__

|Strongly Favor | Favor | Neutral | Against | Strongly Against |
|-|-|-|-|-|
| 10 | 8 | 0 | 0 | 3 |

**Comment by jfbastien** [comment]
See poll here regarding stricter contracts https://github.com/cplusplus/papers/issues/2022
