### ISSUE TITLE
P1403 Experience Report: Implementing a Coroutines TS Frontend to an Existing Tasking Library

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#190]
[P1403R0](https://wg21.link/p1403r0) Experience Report: Implementing a Coroutines TS Frontend to an Existing Tasking Library (David S. Hollman)

**Comment by jensmaurer** [comment]
[EWG in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1403R0-EWG)

**Comment by ogiroux** [comment]
Paper not intended for SG1.

**Comment by jfbastien** [comment]
I don't think we need to discuss this experience report since coroutines are in C++20, and the paper was seen by EWG.
