### ISSUE TITLE
P1408 Abandon observer_ptr

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#194]
[P1408R0](https://wg21.link/p1408r0) Abandon observer_ptr (Bjarne Stroustrup)

**Comment by tituswinters** [comment]
Drop observer_ptr from the TS (as directed in the paper).
SF F N A SA
7  9 7 7 4

Aim to move observer_ptr to Annex D of the WD (deprecated).
SF F N A SA
5  6 5 13 6

Aim to move observer_ptr toward the WD, no special policy.
SF F N A SA
2  4 4 14 12

Aim to move observer_ptr toward the WD, with LEWG policy to ignore it in the standard.
SF F N A SA
4  8 9 5 8

No consensus for any motion.
