### ISSUE TITLE
Implementing borrow checking in C++

### ISSUE THREAD

**Issue by rogerorr** [cplusplus/papers#1984]
Issue for the presentation by Sean Baxter to SG23 on 2024-06-25

**Comment by rogerorr** [comment]
__POLL: We should promise more committee time on borrow checking, knowing that our time is scarceand this will leave less time for other work.__

| SF | WF | N | WA | SA |
| - | - | - | - | - |
| 20 | 7 | 1 | 0 | 0 |

**Comment by unsafe-andrew** [comment]
literally 1984

**Comment by grepwood** [comment]
What version of the language will this feature come to?

**Comment by jensmaurer** [comment]
This issue tracker is for administrative purposes of the WG21 subgroup chairs. In any case, ship vehicles are subject to many factors that are off-topic to discuss in this tracker. Please contact the author directly.

**Comment by cor3ntin** [comment]
@rogerorr Maybe we should close that in favor of #2045 which is the actual paper ?

**Comment by rogerorr** [comment]
Subsumed by #2045 now there is a published paper
