### ISSUE TITLE
P1428 Subscripts and sizes should be signed

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#205]
[P1428R0](https://wg21.link/p1428r0) Subscripts and sizes should be signed (Bjarne Stroustrup)

**Comment by tituswinters** [comment]
Presented, no action required.

**Comment by jensmaurer** [comment]
Probably mooted by [P1227](https://wg21.link/p1227) Signed ssize() functions, unsigned size() functions #150.
