### ISSUE TITLE
P1447 constexpr C++ is not constexpr C

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#214]
[P1447R0](https://wg21.link/p1447r0) constexpr C++ is not constexpr C (Mat&#250;&#353; Chochl&#237;k, Axel Naumann, and David Sankel)

**Comment by jensmaurer** [comment]
Titus Winters: Will process in LEWG first.

**Comment by chandlerc** [comment]
Removing non-SG7 tags / projects.

**Comment by jensmaurer** [comment]
[SG7 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1447r0-SG7)

**Comment by chandlerc** [comment]
This was presented in Kona and the authors are currently pursuing an alternative approach AFAIK with a fresh paper. It can be re-opened if they return to this approach with a new revision.
