### ISSUE TITLE
P1453 Modularizing the Standard Library is a Reorganization Opportunity

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#218]
[P1453R0](https://wg21.link/p1453r0) Modularizing the Standard Library is a Reorganization Opportunity (Bryce Adelstein Lelbach)

**Comment by tituswinters** [comment]
Do not consider option #4 (reorganize std into modules and fix freestanding in C++20).
Unanimous consent

Reserve modules with names prefixed by std, and std+(any sequence of digits) for use by the IS. Implementers may only provide modules matching such prefixes with a reserved token (“._”, depending on if that’s allowable in the module syntax) - users may not depend on those portably.
SF F N A SA
10 4 1 1 0

We *eventually* want both an import std and a finer-granularity modularity for the standard library.
SF F N A SA
8  3 3 1 0

For C++20, Do nothing, assume users will import <utility>. Implementers are required to ensure that existing C++ headers are modular to ensure this is portable.
SF F N A SA
0  8 3 2 1

For C++20, Modularize on the existing header structure.
SF F N A SA
0  0 2 6 5

For C++20, One Big module std.
SF F N A SA
2  3 4 3 2

Walter + Chris DiBella will write the "We reserve module names" paper.
Neil Meyers will write the "Implementers must make import <$CXXHEADER> well-formed" paper.
