### ISSUE TITLE
New function for std::vector

### ISSUE THREAD

**Issue by F-et1sh** [cplusplus/papers#2182]
After working on SFML i so hated std::vector (i'm was bad programmer and didn't know about function reserve(), because of that i wasn't understand why std::vector is so slow and just a default array working much faster) that after that i created my own FE2D::dynamic_array in the new project. And there, at early level of knowing C++, i made one nice function - reset()
```C++
// Reset the Size of Dynamic Array to Zero, but it's don't Touches the Real Occupied Memory of Dynamic Array
void reset() { mSize = 0; }
```
Instead of clear() it's just setting mSize to zero. It's very useful in the situations like
```C++
void Render() { // It's called every frame
// Add a sprites to the FE2D::dynamic_array to draw it later
m_Renderer.AddSprite(m_Object_0);
m_Renderer.AddSprite(m_Object_1);
m_Renderer.AddSprite(m_Object_2);
...
// Draw the Sprites and reset the dynamic arrays to prepare it for the next frame
m_Renderer.RenderSprites();
}
```
^
Here reset() working like clear() but just faster and better

In the std::vector or std::deque is no functions like reset() and i want to add it there, especially sometimes i'm getting an errors cuz my FE2D::dynamic_array is not so good like std::vector and i have to use it, but there is no function i need. I think reset() will be nice thing for std::vector.

**Comment by jensmaurer** [comment]
This issue tracker is exclusively intended for administratively tracker papers targeted at WG21.  If you wish to submit a proposal, please see https://isocpp.org/std/submit-a-proposal for the process.

**Comment by F-et1sh** [comment]
> This issue tracker is intended exclusively for administratively tracking papers targeted at WG21. If you wish to submit a proposal, please see https://isocpp.org/std/submit-a-proposal for the process.

Ok, thx
