### ISSUE TITLE
P1465 Function optimization hint attributes: [[always_inline]], [[never_inline]]

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#225]
[P1465R0](https://wg21.link/p1465r0) Function optimization hint attributes: [[always_inline]], [[never_inline]] (David Goldblatt)

**Comment by jfbastien** [comment]
Paper as presented:
SF F N A SA
0  6 4 1  0
(too many doubts about always inline.  No inline useful for debug purposes)
 
Adding Callsite annotations:
SF F N A SA
1  6 3 0  0

**Comment by jfbastien** [comment]
Let's see what P1669 #556's outcome is.

**Comment by jfbastien** [comment]
Erich is putting P1669 on ice.

**Comment by jfbastien** [comment]
Author does not intend to pursue this further given negative reception.
