### ISSUE TITLE
P1416 SG19 Linear Algebra for Data Science and Machine Learning

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#242]
[P1416R0](https://wg21.link/p1416r0) SG19 Linear Algebra for Data Science and Machine Learning (Johann Mabille, Matthieu Brucher)

**Comment by jensmaurer** [comment]
[SG19 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/SG19MinutesP1416)

**Comment by brycelelbach** [comment]
This was discussed in LEWGI at Kona. It's a position paper, there's nothing more to do here I believe.
