### ISSUE TITLE
P1253 Guidelines for when a WG21 proposal should be reviewed by SG16, the text and Unicode study group

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#247]
[P1253R0](https://wg21.link/p1253r0) Guidelines for when a WG21 proposal should be reviewed by SG16, the text and Unicode study group (Steve Downey)

**Comment by tahonermann** [comment]
@brycelelbach and @jfbastien, would you both be amenable to this paper being presented to EWGI and LEWGI (perhaps in a combined session) at Kona?  The goal would be education for proposal authors and feedback on the guidelines themselves.

I'm going to assume yes for now, remove the SG16 label, and add the EWG-I and LEWG-I labels to this issue.

cc: @steve-downey

**Comment by brycelelbach** [comment]
LEWGI also agrees.
