### ISSUE TITLE
P1446 Reconsider the Networking TS for inclusion in C++20

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#251]
[P1446R0](https://wg21.link/p1446r0) Reconsider the Networking TS for inclusion in C++20 (Christopher Kohlhoff)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1446R0-SG1)

**Comment by ogiroux** [comment]
SG1 poll:
    "If P0443 is adopted in the IS, the papers P1322R0 and P0958R1 should be
    applied to the draft of the Networking TS prior to adopting the TS wording
    into the IS or future TS ."
    Unanimous consent.

**Comment by tituswinters** [comment]
Will begin the process of design review for the networking TS during the Cologne meeting. (Not reconsidering landing all of this for C++20.)
