### ISSUE TITLE
P0932 Tightening the constraints on std::function

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#262]
[P0932R0](https://wg21.link/p0932r0) Tightening the constraints on std::function (Aaryaman Sagar)

https://issues.isocpp.org/show_bug.cgi?id=427

Titus Winters 2018-03-28 16:16:59 UTC
Change the wording design so that all uses of INVOKE<R> pick up the change (and thus does not introduce the new SAFE_INVOKE concept).
Unanimous consent

With the expected updated wording above, forward to LWG for C++20.
Unanimous consent

**Comment by jensmaurer** [comment]
[P0932R1](https://wg21.link/p0932r1) Tightening the constraints on std::function (Aaryaman Sagar)

**Comment by mclow** [comment]
Reviewed in LWG on Thursday; changes needed.

**Comment by JeffGarland** [comment]
LWG reviewed on 2021-01-22 telecon.  There were a number of wording concerns to address.  In addition, significant concerns remain with the approach especially in light of upcoming proposal (P2255) to LEWG that would resolve this differently.  In light of this context LWG is waiting before moving forward with this paper. 

https://wiki.edg.com/bin/view/Wg21telecons2021/P0932-20210122
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2255r0.html

**Comment by jwakely** [comment]
This would be resolved by #949

**Comment by cor3ntin** [comment]
@jwakely @JeffGarland Maybe we should just close this, as it is superseded by P2255, and remove it from the LWG priority list so LEWG isn't surprised?

**Comment by jwakely** [comment]
Yes, this is not going to proceed now. We should make sure the author is aware, but I don't think there is anything more for them to do.
