### ISSUE TITLE
P1056 Add lazy coroutine (coroutine task) type

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#267]
[P1056R1](https://wg21.link/p1056r1) Add lazy coroutine (coroutine task) type (Lewis Baker, Gor Nishanov)

https://issues.isocpp.org/show_bug.cgi?id=497

[Rapperswil 2018 SG1 Minutes](http://wiki.edg.com/bin/view/Wg21rapperswil2018/P1056R0)

SG1 affirms the decision for not to have move assignment (as it is in P1056)
SF | F | N | A | SA
-- | -- | -- | -- | --
6 | 11 | 1 | 0 | 0

SG1 is ok with forwarding LEWG for whatever coroutine shipping vehicle we have as long as it not named "std::task"
SF | F | N | A | SA
-- | -- | -- | -- | --
8 | 5 | 9 | 1 | 2

[Rapperswil 2018 LEWG Minutes](http://wiki.edg.com/bin/view/Wg21rapperswil2018/P1056)

Rename to lazy and forward to LWG for wherever coroutines is heading?
SF | F | N | A | SA
-- | -- | -- | -- | --
10 | 7 | 0 | 0 | 0

**Comment by mclow** [comment]
I received an email:
> The paper authors are not currently pursuing having this land for C++20.
> There are still open design questions, such as the paper P1681, which is asking to revisit the design of allocator customisation for this type.
> We will instead target this type for C++23.

**Comment by JeffGarland** [comment]
Given that there are open design issues, and I'm not seeing an LEWG note here I'm adding LEWG tag to this before LWG will address.

**Comment by FabioFracassi** [comment]
### Reviewed during 2020-05-18 Telecon

__Chair:__ Fabio Fracassi

__Champion:__ Lewis Baker

__Minute Taker:__ Ben Craig

__Start Review:__ 2020-05-18 08:07 Pacific

__Start Polling:__ 09:02

__POLL:__ We want to change `std::lazy` to ensure that it always resumes on its associated execution context (as opposed to leaving it to every co_await in the coroutine)

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|5|9|2|0|0|

__Attendance:__ 36

__# of Authors:__ 1

__Author Position:__ SF

That has strong consensus.

__POLL:__ We want to cover the use case of errors without exceptions.

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|7|5|3|0|0|

__Attendance:__ 32

__# of Authors:__ 1

__Author Position:__ SF

That has strong consensus.

__End:__ 9:30

**Comment by cor3ntin** [comment]
Superseeded by #1191
