### ISSUE TITLE
P1294 Proposed resolution for US104: Allocator-aware regular expressions (rev 3)

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#274]
[P1294R0](https://wg21.link/p1294r0) Proposed resolution for US104: Allocator-aware regular expressions (rev 3) (Michael Spertus, John Maddock)

https://issues.isocpp.org/show_bug.cgi?id=9

**Comment by jensmaurer** [comment]
See also http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0269r0.pdf

**Comment by jensmaurer** [comment]
LWG telecon: LEWG to clarify whether they have seen and approved this particular revision of the paper.

**Comment by jensmaurer** [comment]
https://wiki.edg.com/bin/view/Wg21rapperswil2014/N3254
https://wiki.edg.com/bin/view/Wg21lenexa/LEWG9
https://lists.isocpp.org/lib/2018/07/8246.php

"this is an ABI-breaking change, but it would change the name mangling so it would at least not be a silent break"

**Comment by brycelelbach** [comment]
I believe this was discussed in the context of deprecation of <regex>, and the author said they are withdrawing it.
