### ISSUE TITLE
P0544 User Injection of Filesystems

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#279]
[P0544R0](https://wg21.link/p0544r0) User Injection of Filesystems (Titus Winters, Geoffrey Romer)

https://issues.isocpp.org/show_bug.cgi?id=261

**Comment by AlisdairM** [comment]
From off-list conversations, I believe the original authors have dropped interest in this paper, and no further updates are expected.  It should no longer be flagged as interested for LWG in Cologne (unless the original authors want to jump back in and correct me!)

**Comment by tituswinters** [comment]
That's correct.
