### ISSUE TITLE
P0051 C++ generic overload function

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#281]
[P0051R3](https://wg21.link/p0051r3) C++ generic overload function (Vicente J. Botet Escrib&#225;)

https://issues.isocpp.org/show_bug.cgi?id=125

**Comment by jensmaurer** [comment]
Marshall Clow 2018-11-01 05:49:54 UTC

How can this be in "wording review" when http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0051r3.pdf says:

> Proposed wording
> No wording provided until the open point is closed.

**Comment by mclow** [comment]
No wording; not ready for LWG

**Comment by jfbastien** [comment]
Also see P1772 #527

**Comment by ben-craig** [comment]
Design has consensus, but needs wording, and it needs LEWG to do an initial wording review.  Moving from LWG back to LEWG

**Comment by brycelelbach** [comment]
Closing due to more than 1 year of inactivity. Please re-open if further work is expected.
