### ISSUE TITLE
P1069 Inferencing heap objects

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#30]
[P1069R1](https://wg21.link/p1069r1) Inferencing heap objects (Mike Spertus, Walter E. Brown, Stephan T. Lavavej)

**Comment by jensmaurer** [comment]
LEWG-I in Kona: "Forward to LEWG for C++23"

**Comment by brycelelbach** [comment]
[Kona 2019-02 LEWGI Minutes](http://wiki.edg.com/bin/view/Wg21kona2019/P1069)

[P1069R1](https://wg21.link/P1069R1) “CTAD” for std::make_unique/make_shared

__Champion:__ Mike Spertus

__Minute Taker:__ Nathan Myers

__Start Overview:__ 11:12

__Start Discussion:__ 11:30

__Start Polling:__

__POLL: We should promise more committee time to pursuing [P1069R1](https://wg21.link/P1069R1) and forward it to LEWG for C++23, knowing that our time is scarce and this will leave less time for other work.__

__NO OBJECTION TO UNANIMOUS CONSENT__

__Attendance:__ 12

Eric F volunteers to audit the standard library and find the corner cases for this.

__End:__ 11:35

**Comment by brycelelbach** [comment]
The author is exploring language extensions:

> I've been thinking about proposing language changes for NY that would allow P1069 to support non-type template parameters (as well as other applications) so am thinking about waiting for those before reviewing P1069 in Library.

**Comment by brycelelbach** [comment]
Closing due to more than 1 year of inactivity. Please re-open if further work is expected.
