### ISSUE TITLE
P1095 Zero overhead deterministic failure - A unified mechanism for C and C++

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#319]
[P1095R0](https://wg21.link/p1095r0) Zero overhead deterministic failure - A unfied mechanism for C and C++ (Niall Douglas)

**Comment by jensmaurer** [comment]
Marked as "backlog" on [San Diego EWG-I wiki](http://wiki.edg.com/bin/view/Wg21sandiego2018/SG17).

**Comment by jfbastien** [comment]
Removing from EWGI, I think Herb's P0709 should tag-team with this one.

**Comment by erichkeane** [comment]
EWGI discussed this(with its followup N2429) in the [February 9th, 2023](https://wiki.edg.com/bin/view/Wg21issaquah2023/EWGIP1095R0) evening session in Issaquah. 

EWGI believes that compatibility/interopability with any active WG14 proposals is a necessary part of a zero-overhead exception proposal. (That is, if C is likely to do SOMETHING, we are compatible/interoperable).

| SF | F | N | A | SA |
|----|---|---|---|----|
|  3  | 4 | 2 | 0 |  1 |

Result: Consensus


EWGI believes that errno rewriting is a necessary part of a zero-overhead exception proposal.

| SF | F | N | A | SA |
|----|---|---|---|----|
|  0 | 0 | 5| 4 |   0 |

Result: Consensus Against, we don't care about errno.
