### ISSUE TITLE
P1203 modular main()

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/papers#345]
[P1203R0](https://wg21.link/p1203r0) modular main() (Boris Kolpackov, Richard Smith)

**Comment by jfbastien** [comment]
Seen by EWGI in SAN, sent to EWG for feedback. Expect to see again in EWGI.

**Comment by jensmaurer** [comment]
SG2 was declared dormant, re-assigning to EWG.

**Comment by jfbastien** [comment]
Authors have let me know that they are no long pursuing the paper.
