### ISSUE TITLE
P1284 Allowing Inlining of Replaceable Functions

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/papers#347]
[P1284R0](https://wg21.link/p1284r0) Allowing Inlining of Replaceable Functions (Chris Kennelly)

**Comment by jfbastien** [comment]
Seen in SAN along with P1220R0. No consensus to move forward. Author got feedback on how to improve.

**Comment by cor3ntin** [comment]
Given the lack of recent activity and the lack of consensus in San Diego(2018), I'm closing this issue.
It will be reopen if a new revision of the paper is published.
