### ISSUE TITLE
P1220 Controlling When Inline Functions are Emitted

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/papers#348]
[P1220R0](https://wg21.link/p1220r0) Controlling When Inline Functions are Emitted (Chris Kennelly)

**Comment by jfbastien** [comment]
Seen in SAN along with P1284. No consensus to move forward. Author received feedback on what to address.

**Comment by cor3ntin** [comment]
Given the lack of recent activity and the lack of consensus in San Diego(2018), I'm closing this issue.
It will be reopen if a new revision of the paper is published.
