### ISSUE TITLE
P1249 std::forward from std::initializer_list

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/papers#349]
[P1249R0](https://wg21.link/p1249r0) std::forward from std::initializer_list (Alex Christensen)

**Comment by jfbastien** [comment]
Seen in SAN. Want initializer_list fixes, worried about scope / ABI.

**Comment by cor3ntin** [comment]
Given the lack of recent activity since the paper was seen in San Diego(2018), I'm closing this issue.
It will be reopen if a new revision of the paper is published.
