### ISSUE TITLE
P1283 Sharing is Caring

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/papers#352]
[P1283R0](https://wg21.link/p1283r0) Sharing is Caring (Isabella Muerte).

**Comment by jfbastien** [comment]
Seen by EWG-I in SAN.
Interested in collaboration with LEWGI, figure out what to fix.

**Comment by cor3ntin** [comment]
The author informed me that she is no longer pursuing this paper.
If you are interested in pursuing this work further, reach out to her to get the paper's sources.

Closing for now
