### ISSUE TITLE
P1101 Vector Length Agnostic SIMD

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#37]
[P1101R0](https://wg21.link/p1101r0) Vector Length Agnostic SIMD (Mikhail Maltsev, Richard Sandiford)

**Comment by mattkretz** [comment]
[SG1 in Rapperswil](http://wiki.edg.com/bin/view/Wg21rapperswil2018/P1101R0)

**Comment by jfbastien** [comment]
The SG1 poll tells me there's no consensus to move forward, we need more existing practice.

> Encourage continued work in this direction without large body of existing practice
> SF F N A SA
> 0 0 7 8 4
