### ISSUE TITLE
P1193 Explicitly Specified Returns for (Implicit) Conversions

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#51]
[P1193R0](https://wg21.link/p1193r0) Explicitly Specified Returns for (Implicit) Conversions (JeanHeyd Meneide)

**Comment by jfbastien** [comment]
EWGI wasn't able to see this paper in Kona.

**Comment by jfbastien** [comment]
JeanHeyd tells me that this is on hold because Gasper might supersede the paper with his own. Might reopen based on what happens to Gasper.
