### ISSUE TITLE
P1251 A more constexpr bitset

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#58]
[P1251R1](https://wg21.link/p1251r1) A more constexpr bitset (Morris Hafner)

https://issues.isocpp.org/show_bug.cgi?id=545

**Comment by jensmaurer** [comment]
Titus Winters: This has updates that need LEWG review.

**Comment by tituswinters** [comment]
Discussed in LEWG in Cologne - http://wiki.edg.com/bin/view/Wg21cologne2019/P1251

Rebase on the next working draft, revisit the basic_string constexpr’ness, come back to LEWG.
SF F N A SA
2  7 3 0 0

Forward to LWG for C++23.
SF F N A SA
1  6 4 1 0

Preference is to revise the paper after constexpr std::string is resolved and come back. Revision required.

**Comment by cor3ntin** [comment]
This paper has been replaced by #1087
