### ISSUE TITLE
P1259 Merge most of Networking TS into C++ Working Draft

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#61]
[P1259R1](https://wg21.link/p1259r1) Merge most of Networking TS into C++ Working Draft (Detlef Vollmann)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1259R1-SG1)

**Comment by ogiroux** [comment]
SG1 result: nothing new to discuss as per Detlef, removing SG1 keyword.

**Comment by tituswinters** [comment]
LEWG will begin a general review pass on the Networking TS, beginning in Cologne.

**Comment by je4d** [comment]
Detlef advised me that this was targetting C++20. That is no longer an option, so this was not discussed in Belfast and we do not expect to discuss it in the future.
