### ISSUE TITLE
P1293 ostream_joiner

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#64]
[P1293R1](https://wg21.link/p1293r1) ostream_joiner (Mike Spertus, Nathan Wilson)

**Comment by jensmaurer** [comment]
[P1293R2](https://wg21.link/p1293r2) ostream_joiner (Mike Spertus, Nathan Wilson)

**Comment by tituswinters** [comment]
Forward to LWG for C++20.
SF F N A SA
1  3 4 1 0

**Comment by mclow** [comment]
Michael has indicated to me that he will not be bringing this forward for C++20.

**Comment by JeffGarland** [comment]
Attempts to reach the author and confirm that the paper will not be pursued have been unsuccessful.  Will reopen if contacted.
