### ISSUE TITLE
P1341 Unifying Asynchronous APIs in the Standard Library

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#74]
[P1341R0](https://wg21.link/p1341r0) Unifying Asynchronous APIs in the Standard Library (Lewis Baker)

**Comment by tituswinters** [comment]
Also relevant to LEWG interests, readding the LEWG tag.

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1341R0-SG1)

**Comment by ogiroux** [comment]
Author intends to take this paper to LEWG.  Rationale is that SG1 voted
    previously that we want Senders/Receivers to be our long term direction,
    and the authors want to know whether LEWG likes this attempt at sketching
    that direction.

**Comment by brycelelbach** [comment]
Closing as we are preceding with [P2300](https://wg21.link/P2300), as per the discussion at [the 2021-08-03 Library Evolution telecon](https://github.com/cplusplus/papers/issues/1054#issuecomment-892286083).
