### ISSUE TITLE
P1347 Modules: ADL & Internal Linkage

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#76]
[P1347R0](https://wg21.link/p1347r0) Modules: ADL &amp; Internal Linkage (Davis Herring, Nathan Sidwell)

**Comment by jensmaurer** [comment]
[P1347R1](https://wg21.link/p1347r1) Modules: ADL &amp; Internal Linkage (Nathan Sidwell, Davis Herring)

**Comment by jensmaurer** [comment]
[EWG in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1347R1-EWG)

**Comment by villevoutilainen** [comment]
Superseded by https://github.com/cplusplus/papers/issues/377
