### ISSUE TITLE
P1348 An Executor Property for Occupancy of Execution Agents

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#77]
[P1348R0](https://wg21.link/p1348r0) An Executor Property for Occupancy of Execution Agents (Daisy S. Hollman, Jared Hoberock, Lee Howes, Michael Garland, H. Carter Edwards)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1348R0-SG1)

**Comment by tituswinters** [comment]
Discussed in LEWG in http://wiki.edg.com/bin/view/Wg21cologne2019/P1348

Bring LEWG a paper that chooses the namespace for executors and etc.
SF F N A SA
5  7 3 0 0

Put occupancy/occupancy_t into said namespace, forward to LWG for C++23.
SF F N A SA
1  8 5 0 0

**Comment by brycelelbach** [comment]
@JeffGarland given that Library Evolution is no longer pursuing P0443, but is instead moving forward with P2300, I don't think this should be in LWG's queue anymore.

**Comment by JeffGarland** [comment]
@brycelelbach Yep, and thanks.
