### ISSUE TITLE
P1288 Coroutine concepts and metafunctions

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#858]
[P1288R0](https://wg21.link/P1288r0) Coroutine concepts and metafunctions (Lewis Baker)

**Comment by brycelelbach** [comment]
[P1288R0](https://wg21.link/P1288R0): Coroutine Concepts and Metafunctions

[2020-05-12 Library Evolution Telecon Minutes](http://wiki.edg.com/bin/view/Wg21summer2020/P1288#Library-Evolution-2020-05-12)

__Chair:__ Bryce Adelstein Lelbach

__Champion:__ Lewis Baker

__Minute Taker:__ Mark Hoemmen

__Summary:__ This proposal contains three fundamental library components for
  coroutines: concepts, type traits, and some helper functions.
During this review, we focused on the concepts.
Much of our discussion revolved around some of the restrictions and limitations
  of these concepts.
`co_await` is context dependent; the result of a `co_await` expression depends
  on, among other things, the promise type.
This is why `co_await` cannot be used in an unevaluated context like `decltype`.
This makes it challenging to write a concept that accurately answers the question
  "can I `co_await` on this thing".
The proposed concepts can give both false positives and false negatives to this
  question.
We discussed at length the nature of these restrictions and limitations.
We're currently uncomfortable with the concepts as proposed.
We've directed the author to come back with examples of what works and what 
  doesn't work, and to assess how likely users are to encounter these
  limitations.
We've also requested the addition of `*_with_promise` forms of these concepts,
  which take a specific promise type as a parameter.

__Start Review:__ 2020-05-12 10:07 Pacific

When would you want an Awaiter/Awaitable but not care about what type it
  converts to?

Change concept names to `snake_case`.

Three components:
- Concepts `awaiter`, `awaiter_of<R>`, `awaitable`, `awaitable_of<R>`.
- Type traits: `await_result_t`, `awaiter_type_t`.
- Helper function: `get_awaitable`.

Do we need a concept for non-normally awaitable things (e.g. things awaitable
  because promise type provide `await_transform`).

Paper probably needs a revision covering sender/receiver.

Do we want a concept that covers all of the cases?

Do we want these concepts if we don't have the other concepts?

Explore a type trait/builtin that answers the question "does this type have
  a member `await_transform`".

__Start Polling:__ 11:12

__POLL:__ We want `awaiter`/`awaiter_of`/`awaitable`/`awaitable_of` concepts
even if there are things that can be `co_await`d but do not satisfy these
concepts and satisfying these concepts is not sufficient to determine whether
you can `co_await` a type within a particular context.

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|2|5|5|6|0|

__Attendance:__ 35

__# of Authors:__ 1

__Author Position:__ SF

That does not have consensus.

WA: If the concept can't be written in a way that gives an accurate answer,
what is is the value?

WA: I'd want to see more examples of what would work and wouldn't work to change
my mind.

__POLL:__ We want to explore versions of these concepts that take a specific
promise type as a parameter.

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|3|7|5|3|0|

__Attendance:__ 34

__# of Authors:__ 1

__Author Position:__ WF

That has consensus.

__End:__ 11:31

__CONSENSUS: Bring a revision of PNNNNRM (<FEATURE>), with the guidance below
  to Library Evolution for further review.__
   * Rename concepts to `snake_case`.
   * Update the paper to use concepts as they shipped in C++20.
      * Update `awaiter_of`'s `requires` clause right hand side to be
        `convertible_to<Result>` instead of `Result`.
   * Explain the restrictions and limitations of the proposed concepts in
      greater detail.
      * Provide examples of what works and doesn't work.
      * Provide an assessment of how likely users are to encounter these issues.
   * Assess whether there are any language or compiler solutions that could
      minimize the restrictions and limitations of these concepts.
   * Add `*_with_promise` variants of these concepts that take a promise type
      as a parameter.

**Comment by mpusz** [comment]
See here for some implementation ideas: https://github.com/mpusz/mp-coro/blob/main/src/include/mp-coro/concepts.h.

**Comment by brycelelbach** [comment]
Closing due to more than 1 year of inactivity. Please re-open if further work is expected.
