### ISSUE TITLE
P1374 Resolving LWG #2307 for C++20: Consistently Explicit Constructors

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#90]
[P1374R0](https://wg21.link/p1374r0) Resolving [LWG #2307](https://wg21.link/lwg2307) for C++20: Consistently Explicit Constructors (Alisdair Meredith)

**Comment by tituswinters** [comment]
Paper as written (noexcept + UB, novel policy / precedent)
Alisdair’s suggestion (UB, but not noexcept, Throws: Nothing)

Approve the paper as written.
SF F N A SA
0  4 6 4 1

Approve with revisions as per Alisdair’s suggestion (still UB, not noexcept, wording to include “Throws: Nothing”)
SF F  N A SA
4  11 1 0 0

Revise as per Alisdair’s suggestion, forward to LWG for C++20.
Unanimous consent

Alisdair to revise this week.

**Comment by timsong-cpp** [comment]
These notes seem to be from a different paper (`ceil2`?).

**Comment by mclow** [comment]
This was not adopted for C++20. Removing the "C++20" label.

**Comment by JeffGarland** [comment]
Per chair discussion and confirmation from @tituswinters the poll above is NOT for this paper.  This paper needs updates and discussion in LEWG before coming to LWG.

**Comment by brycelelbach** [comment]
Closing due to more than 1 year of inactivity. Please re-open if further work is expected.
