### ISSUE TITLE
LWG3452 Are views really supposed to have strict 𝒪(1) destruction?

### ISSUE THREAD

**Issue by ben-craig** [cplusplus/papers#963]
Issue: https://cplusplus.github.io/LWG/issue3452
Minutes: https://wiki.edg.com/bin/view/Wg21telecons2021/LWG-issues-20210115

We think we need a clear definition of what a view is (and isn't) in order to guide future work that adds or modifies views. We think there's a deeper problem than just a bad example that doesn't match the prose.

**Comment by cor3ntin** [comment]
This has ramifications for #865

**Comment by brycelelbach** [comment]
# 2021-02-16 Library Evolution Telecon

[LWG3452](https://wg21.link/LWG3452): Are views really supposed to have strict 𝒪(1) destruction?

[2021-02-16 Library Evolution Telecon Minutes](http://wiki.edg.com/bin/view/Wg21telecons2021/LWG3452#Library-Evolution-2021-02-16)

__Chair:__ @billy-baker 

__Champion:__ Corentin Jabot

__Minute Taker:__ Inbal Levi

__POLL:__ The shared_ptr part of the example mentioned in LWG3452 should be removed.

|SF|F|N|A|SA|
|4 | 6 |3|1|0 |

__Attendance:__ 25

__Outcome:__ Remove the shared_ptr part.

## Outcome

Send LWG3542 (Are views really supposed to have strict 𝒪(1) destruction?), revised as below, to Library, for C++23, classified as an improvement of an existing feature (P0592 bucket 2 item).
   * Remove the =shared_ptr= part.

**Comment by cor3ntin** [comment]
See #1085 For the paper fixing this issue

**Comment by jwakely** [comment]
Resolved by the adoption of [P2415R2](https://wg21.link/p2415r2) at the October 2021 plenary.
