### ISSUE TITLE
LWG3506 Missing allocator-extended constructors for priority_queue

### ISSUE THREAD

**Issue by ben-craig** [cplusplus/papers#964]
Issue: https://cplusplus.github.io/LWG/issue3506
Minutes: None

LEWG should confirm that it is OK with the suggested change. Adding new constructors (and altering overload sets) definitely strays into design territory, but the LWG consensus is that this is just fixing the class to meet the agreed design (namely that each constructor of an allocator-aware type has an allocator-extended twin, taking the same arguments plus an allocator). Even if LEWG is fine with the change, please go over the issue, so that the group is aware of that agreed design, and more likely to ensure future additions to the library follow that design correctly.

**Comment by brycelelbach** [comment]
# 2021-02-16 Library Evolution Telecon

[P1425R3](https://wg21.link/P1425R3): Iterators pair constructors for `stack` and `queue`

[2021-02-16 Library Evolution Telecon Minutes](http://wiki.edg.com/bin/view/Wg21telecons2021/P1425#Library-Evolution-2021-02-16)

__Chair:__ @billy-baker 

__Champion:__ Corentin Jabot

__Minute Taker:__ Inbal Levi

__POLL:__ LWG should continue review of P1425R3 (B2) with the design changes from R2. 

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|6| 8|0 |0 |0 |

__Attendance:__ 28

__# of Authors:__ 1

__Author Position:__ SF

__Outcome:__ Go back to LWG with R3.

## Outcome

P1425R3 (Iterators pair constructors for stack and queue) will remain in Library and proceed as planned.

**Comment by JeffGarland** [comment]
LWG reviewed the wording of both the paper and the issue in 2021-02-26 telecom.  Approved the wording for the issue and will be forwarded for c++23 at next plenary.  Closing this issue.
