### ISSUE TITLE
P1708 Simple Statistical Functions

### ISSUE THREAD

**Issue by fraggamuffin** [cplusplus/papers#979]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1708r3.pdf
wg21.link/P1708
Passed SG14 review in Dec 2020 meeting
Directing to SG6 and LEWG review.

This document proposes an extension to the C++ library, to support simple statistical functions. Such functions, not
presently found in the standard (including the special math library), frequently arise in scientific and industrial, as
well as general, applications. These functions do exist in Python [1], the foremost competitor to C++ in the area of
machine learning, along with Calc [2], Excel [3], Julia [4], MATLAB [5], PHP [6], R [7], Rust [8], SAS [9], SPSS
[10] and SQL [11]. Further need for such functions has been identified as part of SG19 (machine learning) [12].
This is not the first proposal to move statistics in C++. In 2004, a number of statistical distributions were proposed
in [13]. More such distributions followed in 2006 [14]. Statistical distributions ultimately appeared in the C++11
standard [15]. Distributions, along with statistical tests, are also found in Boost [16]. A series of special mathematical
functions later followed as part of the C++17 standard [17]. A C library, GNU Scientific Library [18], further includes
support for statistics, special functions and histograms.

**Comment by fraggamuffin** [comment]
Correction:
Passed SG19 review in Dec 2020 meeting

**Comment by brycelelbach** [comment]
Closing this issue as there's already an issue tracking this paper: https://wg21.link/P1708/github, e.g. #475

**Comment by brycelelbach** [comment]
I've changed the title of this issue so that the wg21.link service won't accidentally pick this up as the issue for P1708
